// Image catalog — maps keywords to local image paths
// Images served from /images/ in the public directory (Twemoji SVGs)

const imageCatalog = {
  // Shapes (11)
  circle: '/images/shapes/circle.svg',
  cone: '/images/shapes/cone.svg',
  cube: '/images/shapes/cube.svg',
  cylinder: '/images/shapes/cylinder.svg',
  hexagon: '/images/shapes/hexagon.svg',
  pentagon: '/images/shapes/pentagon.svg',
  rectangle: '/images/shapes/rectangle.svg',
  sphere: '/images/shapes/sphere.svg',
  square: '/images/shapes/square.svg',
  star: '/images/shapes/star.svg',
  triangle: '/images/shapes/triangle.svg',

  // Animals (43)
  ant: '/images/vocab/animals/ant.svg',
  bat: '/images/vocab/animals/bat.svg',
  bear: '/images/vocab/animals/bear.svg',
  bee: '/images/vocab/animals/bee.svg',
  bird: '/images/vocab/animals/bird.svg',
  butterfly: '/images/vocab/animals/butterfly.svg',
  camel: '/images/vocab/animals/camel.svg',
  cat: '/images/vocab/animals/cat.svg',
  cow: '/images/vocab/animals/cow.svg',
  crocodile: '/images/vocab/animals/crocodile.svg',
  deer: '/images/vocab/animals/deer.svg',
  dog: '/images/vocab/animals/dog.svg',
  dolphin: '/images/vocab/animals/dolphin.svg',
  duck: '/images/vocab/animals/duck.svg',
  eagle: '/images/vocab/animals/eagle.svg',
  elephant: '/images/vocab/animals/elephant.svg',
  fish: '/images/vocab/animals/fish.svg',
  flamingo: '/images/vocab/animals/flamingo.svg',
  frog: '/images/vocab/animals/frog.svg',
  giraffe: '/images/vocab/animals/giraffe.svg',
  gorilla: '/images/vocab/animals/gorilla.svg',
  hedgehog: '/images/vocab/animals/hedgehog.svg',
  horse: '/images/vocab/animals/horse.svg',
  lion: '/images/vocab/animals/lion.svg',
  lizard: '/images/vocab/animals/lizard.svg',
  monkey: '/images/vocab/animals/monkey.svg',
  mouse: '/images/vocab/animals/mouse.svg',
  owl: '/images/vocab/animals/owl.svg',
  parrot: '/images/vocab/animals/parrot.svg',
  peacock: '/images/vocab/animals/peacock.svg',
  penguin: '/images/vocab/animals/penguin.svg',
  pig: '/images/vocab/animals/pig.svg',
  rabbit: '/images/vocab/animals/rabbit.svg',
  rooster: '/images/vocab/animals/rooster.svg',
  scorpion: '/images/vocab/animals/scorpion.svg',
  sheep: '/images/vocab/animals/sheep.svg',
  snail: '/images/vocab/animals/snail.svg',
  snake: '/images/vocab/animals/snake.svg',
  spider: '/images/vocab/animals/spider.svg',
  swan: '/images/vocab/animals/swan.svg',
  turtle: '/images/vocab/animals/turtle.svg',
  whale: '/images/vocab/animals/whale.svg',
  zebra: '/images/vocab/animals/zebra.svg',

  // Sea life (13)
  clownfish: '/images/vocab/sealife/clownfish.svg',
  coral: '/images/vocab/sealife/coral.svg',
  crab: '/images/vocab/sealife/crab.svg',
  jellyfish: '/images/vocab/sealife/jellyfish.svg',
  lobster: '/images/vocab/sealife/lobster.svg',
  octopus: '/images/vocab/sealife/octopus.svg',
  pufferfish: '/images/vocab/sealife/pufferfish.svg',
  seal: '/images/vocab/sealife/seal.svg',
  shark: '/images/vocab/sealife/shark.svg',
  shell: '/images/vocab/sealife/shell.svg',
  shrimp: '/images/vocab/sealife/shrimp.svg',
  squid: '/images/vocab/sealife/squid.svg',
  sealife_whale: '/images/vocab/sealife/whale.svg',

  // Objects (30)
  airplane: '/images/vocab/objects/airplane.svg',
  bag: '/images/vocab/objects/bag.svg',
  ball: '/images/vocab/objects/ball.svg',
  bed: '/images/vocab/objects/bed.svg',
  bicycle: '/images/vocab/objects/bicycle.svg',
  boat: '/images/vocab/objects/boat.svg',
  book: '/images/vocab/objects/book.svg',
  bus: '/images/vocab/objects/bus.svg',
  camera: '/images/vocab/objects/camera.svg',
  car: '/images/vocab/objects/car.svg',
  chair: '/images/vocab/objects/chair.svg',
  clock: '/images/vocab/objects/clock.svg',
  cup: '/images/vocab/objects/cup.svg',
  door: '/images/vocab/objects/door.svg',
  globe: '/images/vocab/objects/globe.svg',
  guitar: '/images/vocab/objects/guitar.svg',
  hammer: '/images/vocab/objects/hammer.svg',
  hat: '/images/vocab/objects/hat.svg',
  house: '/images/vocab/objects/house.svg',
  key: '/images/vocab/objects/key.svg',
  lamp: '/images/vocab/objects/lamp.svg',
  pencil: '/images/vocab/objects/pencil.svg',
  phone: '/images/vocab/objects/phone.svg',
  rocket: '/images/vocab/objects/rocket.svg',
  scissors: '/images/vocab/objects/scissors.svg',
  ship: '/images/vocab/objects/ship.svg',
  train: '/images/vocab/objects/train.svg',
  truck: '/images/vocab/objects/truck.svg',
  umbrella: '/images/vocab/objects/umbrella.svg',
  window: '/images/vocab/objects/window.svg',

  // Food (30)
  apple: '/images/vocab/food/apple.svg',
  banana: '/images/vocab/food/banana.svg',
  bread: '/images/vocab/food/bread.svg',
  broccoli: '/images/vocab/food/broccoli.svg',
  cake: '/images/vocab/food/cake.svg',
  carrot: '/images/vocab/food/carrot.svg',
  cheese: '/images/vocab/food/cheese.svg',
  cherries: '/images/vocab/food/cherries.svg',
  chicken: '/images/vocab/food/chicken.svg',
  chocolate: '/images/vocab/food/chocolate.svg',
  cookie: '/images/vocab/food/cookie.svg',
  corn: '/images/vocab/food/corn.svg',
  egg: '/images/vocab/food/egg.svg',
  grapes: '/images/vocab/food/grapes.svg',
  hamburger: '/images/vocab/food/hamburger.svg',
  icecream: '/images/vocab/food/icecream.svg',
  lollipop: '/images/vocab/food/lollipop.svg',
  milk: '/images/vocab/food/milk.svg',
  orange: '/images/vocab/food/orange.svg',
  peach: '/images/vocab/food/peach.svg',
  pineapple: '/images/vocab/food/pineapple.svg',
  pizza: '/images/vocab/food/pizza.svg',
  popcorn: '/images/vocab/food/popcorn.svg',
  potato: '/images/vocab/food/potato.svg',
  rice: '/images/vocab/food/rice.svg',
  strawberry: '/images/vocab/food/strawberry.svg',
  taco: '/images/vocab/food/taco.svg',
  tomato: '/images/vocab/food/tomato.svg',
  water: '/images/vocab/food/water.svg',
  watermelon: '/images/vocab/food/watermelon.svg',

  // Nature (24)
  beach: '/images/vocab/nature/beach.svg',
  cactus: '/images/vocab/nature/cactus.svg',
  cloud: '/images/vocab/nature/cloud.svg',
  clover: '/images/vocab/nature/clover.svg',
  desert: '/images/vocab/nature/desert.svg',
  flower: '/images/vocab/nature/flower.svg',
  forest: '/images/vocab/nature/forest.svg',
  hibiscus: '/images/vocab/nature/hibiscus.svg',
  leaf: '/images/vocab/nature/leaf.svg',
  lightning: '/images/vocab/nature/lightning.svg',
  moon: '/images/vocab/nature/moon.svg',
  mountain: '/images/vocab/nature/mountain.svg',
  mushroom: '/images/vocab/nature/mushroom.svg',
  palmtree: '/images/vocab/nature/palmtree.svg',
  rain: '/images/vocab/nature/rain.svg',
  rainbow: '/images/vocab/nature/rainbow.svg',
  rose: '/images/vocab/nature/rose.svg',
  sea: '/images/vocab/nature/sea.svg',
  seedling: '/images/vocab/nature/seedling.svg',
  snowflake: '/images/vocab/nature/snowflake.svg',
  nature_star: '/images/vocab/nature/star.svg',
  sun: '/images/vocab/nature/sun.svg',
  tree: '/images/vocab/nature/tree.svg',
  volcano: '/images/vocab/nature/volcano.svg',

  // Body (12)
  bone: '/images/vocab/body/bone.svg',
  brain: '/images/vocab/body/brain.svg',
  ear: '/images/vocab/body/ear.svg',
  eye: '/images/vocab/body/eye.svg',
  foot: '/images/vocab/body/foot.svg',
  hand: '/images/vocab/body/hand.svg',
  heart: '/images/vocab/body/heart.svg',
  lungs: '/images/vocab/body/lungs.svg',
  mouth: '/images/vocab/body/mouth.svg',
  muscle: '/images/vocab/body/muscle.svg',
  nose: '/images/vocab/body/nose.svg',
  teeth: '/images/vocab/body/teeth.svg',

  // Places (17)
  airport: '/images/vocab/places/airport.svg',
  bank: '/images/vocab/places/bank.svg',
  castle: '/images/vocab/places/castle.svg',
  church: '/images/vocab/places/church.svg',
  construction: '/images/vocab/places/construction.svg',
  factory: '/images/vocab/places/factory.svg',
  fountain: '/images/vocab/places/fountain.svg',
  gasstation: '/images/vocab/places/gasstation.svg',
  home: '/images/vocab/places/home.svg',
  hospital: '/images/vocab/places/hospital.svg',
  hotel: '/images/vocab/places/hotel.svg',
  mosque: '/images/vocab/places/mosque.svg',
  postoffice: '/images/vocab/places/postoffice.svg',
  school: '/images/vocab/places/school.svg',
  shop: '/images/vocab/places/shop.svg',
  stadium: '/images/vocab/places/stadium.svg',
  store: '/images/vocab/places/store.svg',

  // Actions (14)
  cook: '/images/vocab/actions/cook.svg',
  cycle: '/images/vocab/actions/cycle.svg',
  dance: '/images/vocab/actions/dance.svg',
  exercise: '/images/vocab/actions/exercise.svg',
  music: '/images/vocab/actions/music.svg',
  paint: '/images/vocab/actions/paint.svg',
  play: '/images/vocab/actions/play.svg',
  read: '/images/vocab/actions/read.svg',
  run: '/images/vocab/actions/run.svg',
  sing: '/images/vocab/actions/sing.svg',
  sleep: '/images/vocab/actions/sleep.svg',
  swim: '/images/vocab/actions/swim.svg',
  walk: '/images/vocab/actions/walk.svg',
  write: '/images/vocab/actions/write.svg',

  // Science (16)
  battery: '/images/vocab/science/battery.svg',
  blood: '/images/vocab/science/blood.svg',
  chemistry: '/images/vocab/science/chemistry.svg',
  dna: '/images/vocab/science/dna.svg',
  earth: '/images/vocab/science/earth.svg',
  gear: '/images/vocab/science/gear.svg',
  science_leaf: '/images/vocab/science/leaf.svg',
  lightbulb: '/images/vocab/science/lightbulb.svg',
  magnet: '/images/vocab/science/magnet.svg',
  microscope: '/images/vocab/science/microscope.svg',
  plant: '/images/vocab/science/plant.svg',
  seed: '/images/vocab/science/seed.svg',
  science_star: '/images/vocab/science/star.svg',
  telescope: '/images/vocab/science/telescope.svg',
  testtube: '/images/vocab/science/testtube.svg',
  thermometer: '/images/vocab/science/thermometer.svg',
};

// Get image path for a keyword (case-insensitive)
export function getImagePath(keyword) {
  return imageCatalog[keyword.toLowerCase()] || null;
}

// Get all available keywords
export function getAvailableImages() {
  return Object.keys(imageCatalog);
}

// Check if an image exists in the catalog
export function hasImage(keyword) {
  return keyword.toLowerCase() in imageCatalog;
}

export default imageCatalog;
