-- V15: Phase 4-5 tables — Parent Dashboard, Story Mode, Learning Needs
-- Parent can set PIN, add notes, track behavioral observations, specialist reports
-- Story mode progress tracking
-- Learning needs (dyslexia, ADHD, autism, dyscalculia)

-- Parent PIN for dashboard access
CREATE TABLE IF NOT EXISTS parent_pins (
  id SERIAL PRIMARY KEY,
  profile_id INT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  pin_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(profile_id)
);
CREATE INDEX IF NOT EXISTS idx_parent_pins_profile ON parent_pins(profile_id);

-- Parent notes on child profile
CREATE TABLE IF NOT EXISTS parent_notes (
  id SERIAL PRIMARY KEY,
  profile_id INT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  note TEXT NOT NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'normal',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_parent_notes_profile ON parent_notes(profile_id);

-- Learning needs flags
CREATE TABLE IF NOT EXISTS learning_needs (
  id SERIAL PRIMARY KEY,
  profile_id INT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  dyslexia BOOLEAN NOT NULL DEFAULT FALSE,
  adhd BOOLEAN NOT NULL DEFAULT FALSE,
  autism BOOLEAN NOT NULL DEFAULT FALSE,
  dyscalculia BOOLEAN NOT NULL DEFAULT FALSE,
  other_notes TEXT,
  source VARCHAR(20) NOT NULL DEFAULT 'parent',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(profile_id)
);
CREATE INDEX IF NOT EXISTS idx_learning_needs_profile ON learning_needs(profile_id);

-- Behavioral observations (tracked automatically during sessions)
CREATE TABLE IF NOT EXISTS behavioral_observations (
  id SERIAL PRIMARY KEY,
  profile_id INT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  observation_type VARCHAR(50) NOT NULL,
  details JSONB,
  session_type VARCHAR(30),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_behavioral_obs_profile ON behavioral_observations(profile_id);
CREATE INDEX IF NOT EXISTS idx_behavioral_obs_type ON behavioral_observations(profile_id, observation_type, created_at DESC);

-- Specialist reports (generated by AI for parents)
CREATE TABLE IF NOT EXISTS specialist_reports (
  id SERIAL PRIMARY KEY,
  profile_id INT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  report_data JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_specialist_reports_profile ON specialist_reports(profile_id);

-- Story mode progress (The 7 Lost Books of Knowledge)
CREATE TABLE IF NOT EXISTS story_progress (
  id SERIAL PRIMARY KEY,
  profile_id INT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  chapter INT NOT NULL,
  stage INT NOT NULL,
  score INT NOT NULL DEFAULT 0,
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(profile_id, chapter, stage)
);
CREATE INDEX IF NOT EXISTS idx_story_progress_profile ON story_progress(profile_id);