// curriculum-english.js
// Source: Cambridge Primary English Framework 0844/0058
const english = {
  1: [
    {
      id: 'english-1-phonics',
      name: 'Phonics and Word Reading',
      strand: 'Reading',
      codes: ['1Rw.01', '1Rw.02', '1Rw.03', '1Rw.04', '1Rw.05', '1Rw.06', '1Rw.07'],
      objectives: [
        'Know the name of each letter in the English alphabet and the most common sound (phoneme) associated with it',
        'Identify sounds represented by multiple letters (digraphs/trigraphs)',
        'Blend adjacent consonant sounds',
        'Read verbs with -s, -ed, -ing endings',
        'Use phonics to read decodable words',
        'Sound out unfamiliar word elements using phonics',
        'Begin to recognise a range of common words on sight',
      ],
    },
    {
      id: 'english-1-reading-comprehension',
      name: 'Reading Comprehension',
      strand: 'Reading',
      codes: [
        '1Rs.01', '1Rs.02', '1Rs.03', '1Rs.04',
        '1Ri.01', '1Ri.02', '1Ri.03', '1Ri.04', '1Ri.05', '1Ri.06', '1Ri.07',
        '1Ri.08', '1Ri.09', '1Ri.10', '1Ri.11', '1Ri.12', '1Ri.13', '1Ri.14',
        '1Ra.01', '1Ra.02', '1Ra.03', '1Ra.04', '1Ra.05', '1Ra.06',
      ],
      objectives: [
        'Talk about the sequence of events or actions in a text',
        'Explore and recognise features of text structure in different fiction and non-fiction texts',
        'Explore book parts (cover, title, contents)',
        'Explore and recognise how texts for different purposes look different',
        'Read and explore a range of simple stories and poems',
        'Identify characteristics of simple stories',
        'Read and explore a range of simple non-fiction text types',
        'Begin to show awareness that different non-fiction text types have different purposes',
        'Explore explicit meanings in simple texts',
        'Retell a familiar story verbally',
        'Identify the main characters in a story and talk about what happens to them',
        'Find information from labels, lists, captions',
        'Explore implicit meanings in simple texts',
        'Anticipate story progression',
        'Make simple text inferences',
        'Respond verbally to simple questions about texts',
        'Answer questions about texts with some explanation of thinking',
        'Show understanding of rhyme and repetition when joining in with reading',
        'Enjoy reading and hearing a range of simple stories, poems and non-fiction texts',
        'Join in with some words and phrases when reading familiar simple stories and poems',
        'Read simple texts independently aloud',
        'Talk about texts heard or read, including making links with own experiences',
        'Make beginning choices about pleasure reading',
        'Begin to identify how contexts and events in stories are the same as or different from real life',
      ],
    },
    {
      id: 'english-1-vocabulary',
      name: 'Vocabulary',
      strand: 'Reading',
      codes: ['1Rv.01', '1Rv.02', '1Rv.03', '1Rv.04', '1Rv.05'],
      objectives: [
        'Begin to show understanding of words and sentences encountered in reading',
        'Use pictures as cues for unfamiliar words',
        'Identify and record interesting and significant words from texts',
        'Recite the alphabet in order',
        'Explore sounds and words in texts, e.g. rhyming words, rhythm',
      ],
    },
    {
      id: 'english-1-grammar-punctuation',
      name: 'Grammar and Punctuation',
      strand: 'Writing',
      codes: [
        '1Rg.01', '1Rg.02', '1Rg.03', '1Rg.04', '1Rg.05', '1Rg.06', '1Rg.07',
        '1Wg.01', '1Wg.02', '1Wg.03', '1Wg.04', '1Wg.05', '1Wg.06',
      ],
      objectives: [
        'Understand capitals, full stops, and grammatical sentence links',
        'Explore in texts the use of full stops and different uses of capital letters',
        'Identify sentences in texts',
        'Explore in texts sentences that contain "and"',
        'Understand statement grammar including verbs and word order',
        'Identify nouns and verbs',
        'Understand articles (the, a, an)',
        'Use a capital letter and full stop to start and end a sentence',
        'End some sentences with full stops in extended writing',
        'Capitalise "I", proper nouns, and some sentence starts',
        'Write simple sentences',
        'Use "and" to join words and clauses',
        'Use articles appropriately',
      ],
    },
    {
      id: 'english-1-spelling',
      name: 'Spelling',
      strand: 'Writing',
      codes: ['1Ww.01', '1Ww.02', '1Ww.03', '1Ww.04', '1Ww.05', '1Ww.06', '1Ww.07'],
      objectives: [
        'Identify graphemes associated with sounds',
        'Identify letters for consonant combinations and digraphs',
        'Relate rhyme patterns to spelling',
        'Use plural endings -s and -es',
        'Choose plausible graphemes that match phonemes to write simple regular words',
        'Spell familiar words including common exceptions',
        'Ask for support in spelling unfamiliar words and use spelling logs',
      ],
    },
    {
      id: 'english-1-writing-composition',
      name: 'Writing Composition',
      strand: 'Writing',
      codes: [
        '1Wv.01', '1Wv.02', '1Wv.03',
        '1Ws.01', '1Ws.02',
        '1Wc.01', '1Wc.02', '1Wc.03', '1Wc.04', '1Wc.05',
        '1Wp.01', '1Wp.02', '1Wp.03', '1Wp.04', '1Wp.05', '1Wp.06',
      ],
      objectives: [
        'Use vocabulary relevant to familiar topics',
        'Begin to use some formulaic language (e.g. "Once upon a time")',
        'Use word lists to extend vocabulary in writing',
        'Develop a simple sequence of known actions or events',
        'Use simple organisational features appropriate to the text type',
        'Begin to write simple stories and poems, including using structures of familiar stories',
        'Plan writing by speaking aloud',
        'Develop a short written retelling of a familiar story',
        'Begin to write for a purpose using basic language and features appropriate for the text type',
        'Include relevant information in simple non-fiction',
        'Develop efficient pencil grip',
        'Form letters correctly',
        'Join some letters',
        'Record answers about texts',
        'Present text in a range of different ways',
        'Read own writing aloud',
      ],
    },
    {
      id: 'english-1-speaking-listening',
      name: 'Speaking and Listening',
      strand: 'Speaking and Listening',
      codes: [
        '1SLm.01', '1SLm.02', '1SLm.03', '1SLm.04', '1SLm.05',
        '1SLs.01', '1SLs.02',
        '1SLg.01', '1SLg.02', '1SLg.03', '1SLg.04',
        '1SLp.01', '1SLp.02', '1SLp.03', '1SLp.04', '1SLp.05',
        '1SLr.01', '1SLr.02',
      ],
      objectives: [
        'Speak clearly with familiar people',
        'Provide relevant information',
        'Use vocabulary to describe events and feelings',
        'Show non-verbal communication techniques',
        'Show listener awareness',
        'Listen and follow simple instruction sequences',
        'Ask simple comprehension questions',
        'Work with others in groups',
        'Show understanding of others\' opinions',
        'Listen without interrupting',
        'Take turns speaking, express feelings and ideas',
        'Re-read sentences aloud with some fluency and expression',
        'Recite simple poems, showing awareness of rhythm',
        'Pause at full stops when reading',
        'Engage in imaginative play enacting characters',
        'Make simple personal statements',
        'Discuss enjoyed activities',
        'Suggest how non-verbal communication reflects feelings',
      ],
    },
  ],
  2: [
    {
      id: 'english-2-phonics',
      name: 'Phonics and Word Reading',
      strand: 'Reading',
      codes: ['2Rw.01', '2Rw.02', '2Rw.03', '2Rw.04', '2Rw.05', '2Rw.06', '2Rw.07'],
      objectives: [
        'Identify common ways in which graphemes can be pronounced differently',
        'Read words with split digraphs (e.g. made, like)',
        'Read words with common prefixes and suffixes (un-, dis-, re-, -er, -est, -ly, -y, -ful)',
        'Read familiar words quickly without sounding or blending',
        'Use phonics to decode unfamiliar words',
        'Read multi-syllabic and compound words by segmenting',
        'Extend the range of common words recognised on sight',
      ],
    },
    {
      id: 'english-2-reading-comprehension',
      name: 'Reading Comprehension',
      strand: 'Reading',
      codes: [
        '2Rs.01', '2Rs.02', '2Rs.03',
        '2Ri.01', '2Ri.02', '2Ri.03', '2Ri.04', '2Ri.05', '2Ri.06', '2Ri.07',
        '2Ri.08', '2Ri.09', '2Ri.10', '2Ri.11', '2Ri.12', '2Ri.13', '2Ri.14',
        '2Ri.15', '2Ri.16',
        '2Ra.01', '2Ra.02', '2Ra.03', '2Ra.04', '2Ra.05',
      ],
      objectives: [
        'Talk about event and idea sequences',
        'Explore and recognise features of text structure in different fiction and non-fiction texts',
        'Explore and recognise organisational features that help the reader',
        'Distinguish between fiction and non-fiction',
        'Read and explore a range of simple stories and poems',
        'Identify characteristics of simple stories',
        'Read and explore a range of simple non-fiction text types',
        'Begin to show awareness that different non-fiction text types have different purposes',
        'Explore explicit meanings in simple texts',
        'Identify and use the main events to retell a story verbally',
        'Describe story settings and characters',
        'Find information from visual sources',
        'Explore implicit meanings in simple texts',
        'Predict story endings',
        'Make simple inferences',
        'Answer simple questions from reading',
        'Locate information using contents pages',
        'Answer questions about texts with some explanation of thinking',
        'Talk about patterns in stories and poems',
        'Enjoy reading and hearing a range of simple stories, poems and non-fiction texts',
        'Begin to read texts silently as well as aloud',
        'Discuss texts read or heard, including giving reasons for likes and dislikes',
        'Make choices about pleasure reading',
        'Recognise that stories may be from different times and places',
      ],
    },
    {
      id: 'english-2-vocabulary',
      name: 'Vocabulary',
      strand: 'Reading',
      codes: ['2Rv.01', '2Rv.02', '2Rv.03', '2Rv.04', '2Rv.05'],
      objectives: [
        'Identify possible meanings of unfamiliar words',
        'Identify and record interesting and significant words from texts',
        'Use the initial letter to organise words in alphabetical order',
        'Explore and comment on sounds and words in texts, including adjectives',
        'Explore different ways of beginning sentences in texts',
      ],
    },
    {
      id: 'english-2-grammar-punctuation',
      name: 'Grammar and Punctuation',
      strand: 'Writing',
      codes: [
        '2Rg.01', '2Rg.02', '2Rg.03', '2Rg.04', '2Rg.05', '2Rg.06',
        '2Wg.01', '2Wg.02', '2Wg.03', '2Wg.04', '2Wg.05', '2Wg.06',
        '2Wg.07', '2Wg.08', '2Wg.09', '2Wg.10',
      ],
      objectives: [
        'Show understanding of punctuation, including speech marks, and simple grammar',
        'Explore and understand the differences in use of full stops and question marks',
        'Explore in texts sentences that contain and, but, because, if, when',
        'Explore and understand the grammar of commands/instructions and questions',
        'Explore and understand examples of nouns and noun phrases',
        'Explore examples of pronouns in texts, including their purpose',
        'Use capital letters, full stops and question marks correctly in simple sentences',
        'Explore and use commas to separate items in lists',
        'Begin to include direct speech in writing, using a new line for each speaker',
        'Write clear statements, commands, questions',
        'Write simple sentences and multi-clause sentences using and, but, or',
        'Begin to write multi-clause sentences using simple connectives',
        'Begin to use suffixes -s, -ing and -ed appropriately',
        'Use simple quantifiers appropriately',
        'Use pronouns with grammatical agreement',
        'Use adjectives including comparative and superlative forms',
      ],
    },
    {
      id: 'english-2-spelling',
      name: 'Spelling',
      strand: 'Writing',
      codes: [
        '2Ww.01', '2Ww.02', '2Ww.03', '2Ww.04', '2Ww.05',
        '2Ww.06', '2Ww.07', '2Ww.08', '2Ww.09', '2Ww.10',
      ],
      objectives: [
        'Explore and use different spellings of common phonemes, including long vowel phonemes',
        'Explore and use spellings of words with split digraphs',
        'Relate rhyme to known spelling patterns (e.g. whale, snail)',
        'Use common irregular plurals',
        'Use verb endings -s, -ed, -ing without root changes',
        'Spell words with common prefixes and suffixes',
        'Explore and use words which sound the same but have different spellings (homophones)',
        'Use knowledge of phonemes and spelling patterns to spell common regular words',
        'Spell common exception words accurately',
        'Ask for support in spelling unfamiliar words and use spelling logs',
      ],
    },
    {
      id: 'english-2-writing-composition',
      name: 'Writing Composition',
      strand: 'Writing',
      codes: [
        '2Wv.01', '2Wv.02', '2Wv.03', '2Wv.04', '2Wv.05',
        '2Ws.01', '2Ws.02', '2Ws.03',
        '2Wc.01', '2Wc.02', '2Wc.03', '2Wc.04', '2Wc.05',
        '2Wp.01', '2Wp.02', '2Wp.03', '2Wp.04', '2Wp.05', '2Wp.06',
      ],
      objectives: [
        'Use vocabulary relevant to familiar topics',
        'In story writing, use a range of adjectives to describe characters and settings',
        'Begin to vary sentence openings, including using language of time',
        'Choose and use interesting words and phrases',
        'Use word lists to extend vocabulary',
        'Write a sequence of events or ideas, including stories with a beginning, middle and end',
        'Group sentences relating to similar ideas',
        'Use simple organisational features appropriate to the text type',
        'Begin to write simple stories and poems, including using structures of familiar stories',
        'Plan writing through discussion',
        'Include descriptions of settings and characters in stories',
        'Begin to write for a purpose using basic language and features appropriate for the text type',
        'Include additional information in non-fiction texts',
        'Ensure letter consistency, size, proportion, word spacing',
        'Know how to join letters and which to leave unjoined',
        'Record key information from non-fiction',
        'Present text in a range of different ways',
        'Read writing to others and share improvements',
        'Begin to proofread for errors by re-reading own writing aloud',
      ],
    },
    {
      id: 'english-2-speaking-listening',
      name: 'Speaking and Listening',
      strand: 'Speaking and Listening',
      codes: [
        '2SLm.01', '2SLm.02', '2SLm.03', '2SLm.04', '2SLm.05',
        '2SLs.01', '2SLs.02',
        '2SLg.01', '2SLg.02', '2SLg.03', '2SLg.04',
        '2SLp.01', '2SLp.02', '2SLp.03', '2SLp.04',
        '2SLr.01', '2SLr.02', '2SLr.03',
      ],
      objectives: [
        'Speak clearly and confidently',
        'Provide relevant information with detail',
        'Use vocabulary for events and feelings',
        'Use non-verbal communication techniques',
        'Show listener awareness',
        'Listen and respond appropriately, recalling main points',
        'Ask comprehension questions',
        'Work in groups',
        'Understand others\' opinions',
        'Respond relevantly in discussions',
        'Take turns, add relevant information',
        'Read familiar stories and poems aloud with fluency and expression',
        'Show awareness of speech marks when reading aloud',
        'Extend experiences through role-play',
        'Deliver short presentations',
        'Talk about own activities and choices',
        'Discuss others\' presentations',
        'Identify non-verbal and verbal communication match',
      ],
    },
  ],
  3: [
    {
      id: 'english-3-phonics',
      name: 'Phonics and Word Reading',
      strand: 'Reading',
      codes: ['3Rw.01', '3Rw.02', '3Rw.03', '3Rw.04'],
      objectives: [
        'Identify less common ways in which graphemes can be pronounced',
        'Read words with an apostrophe to mark omission of letters',
        'Use effective strategies to read unfamiliar words, including using phonic knowledge',
        'Extend the range of common words recognised on sight',
      ],
    },
    {
      id: 'english-3-reading-comprehension',
      name: 'Reading Comprehension',
      strand: 'Reading',
      codes: [
        '3Rs.01', '3Rs.02', '3Rs.03', '3Rs.04',
        '3Ri.01', '3Ri.02', '3Ri.03', '3Ri.04', '3Ri.05', '3Ri.06', '3Ri.07',
        '3Ri.08', '3Ri.09', '3Ri.10', '3Ri.11', '3Ri.12', '3Ri.13', '3Ri.14',
        '3Ri.15', '3Ri.16', '3Ri.17',
        '3Ra.01', '3Ra.02', '3Ra.03', '3Ra.04', '3Ra.05',
      ],
      objectives: [
        'Explore and describe how events or ideas in a text relate to earlier or later events',
        'Explore and recognise key features of text structure in different fiction and non-fiction texts',
        'Explore and recognise different ways that information is organised in texts',
        'Explore and recognise how sentence openings in texts establish links between sentences',
        'Understand the difference between fiction and non-fiction and locate books by classification',
        'Read and explore a range of fiction genres, poems and playscripts',
        'Identify, discuss and compare different fiction genres and their typical characteristics',
        'Read and explore a range of non-fiction text types',
        'Identify, discuss and compare the purposes and features of different non-fiction text types',
        'Explore explicit meanings in a range of texts',
        'Identify main points or gist from reading',
        'Explain how settings and characters are developed',
        'Follow written instructions to carry out activities',
        'Explore implicit meanings in a range of texts',
        'Predict story endings based on story knowledge',
        'Make inferences from texts, including about the feelings, thoughts and motives of characters',
        'Begin to distinguish between fact and opinion in texts',
        'Scan texts for specific information',
        'Locate information using indexes',
        'Answer questions with reference to text points',
        'Recognise text themes',
        'Enjoy independent and shared reading of fiction genres, poems, playscripts and non-fiction texts',
        'Read texts silently',
        'Share a review of a text, summarising what it is about and expressing opinions',
        'Make pleasure reading choices based on blurbs and reviews',
        'Compare different retellings of the same story',
      ],
    },
    {
      id: 'english-3-vocabulary',
      name: 'Vocabulary',
      strand: 'Reading',
      codes: ['3Rv.01', '3Rv.02', '3Rv.03', '3Rv.04', '3Rv.05', '3Rv.06', '3Rv.07'],
      objectives: [
        'Deduce unfamiliar word meanings from context',
        'Identify and record interesting and significant words, and synonyms, from texts',
        'Use the initial two letters to organise words in alphabetical order',
        'Explore and comment on words in texts that make an impact on the reader',
        'Explore and comment on how a writer\'s choice of verbs to introduce and conclude dialogue',
        'Explore how different sentence openings are used for different purposes',
        'Identify simple figurative language in texts, including sound effects and simple onomatopoeia',
      ],
    },
    {
      id: 'english-3-grammar-punctuation',
      name: 'Grammar and Punctuation',
      strand: 'Writing',
      codes: [
        '3Rg.01', '3Rg.02', '3Rg.03', '3Rg.04', '3Rg.05', '3Rg.06',
        '3Rg.07', '3Rg.08', '3Rg.09', '3Rg.10', '3Rg.11',
        '3Wg.01', '3Wg.02', '3Wg.03', '3Wg.04', '3Wg.05', '3Wg.06',
        '3Wg.07', '3Wg.08',
      ],
      objectives: [
        'Use knowledge of punctuation and grammar to read familiar texts with understanding',
        'Explore and understand the use of exclamation marks',
        'Explore and understand the use of apostrophes to mark omission of letters',
        'Explore and understand similarities and differences between punctuation of narrative and direct speech',
        'Explore and understand grammar and purpose of different types of sentences',
        'Explore and understand grammar of multi-clause sentences, including conditional sentences',
        'Explore purpose and grammar of nouns, verbs, adjectives',
        'Identify nouns, pronouns, verbs, adjectives in texts',
        'Explore preposition purposes',
        'Explore and identify past and present verb forms in texts, including irregular verbs',
        'Identify common irregular verb forms in the past tense',
        'Use full stops, question marks and exclamation marks correctly in different types of sentences',
        'Use apostrophes for omissions',
        'Use speech marks for direct speech',
        'Use different types of sentences and their grammar appropriately',
        'Write multi-clause sentences using simple connectives of time, place and cause',
        'Use regular verb forms accurately',
        'Use common irregular past tense forms',
        'Use prepositions accurately',
      ],
    },
    {
      id: 'english-3-spelling',
      name: 'Spelling',
      strand: 'Writing',
      codes: ['3Ww.01', '3Ww.02', '3Ww.03', '3Ww.04', '3Ww.05', '3Ww.06'],
      objectives: [
        'Explore and use common ways in which consonant phonemes can be represented',
        'Use recognition of long and short vowel sounds and spelling rules to add -s, -ed and -ing',
        'Spell words with a range of common prefixes and suffixes (re-, in-, -ment, -ness, -less)',
        'Spell common homophones correctly to match their meaning',
        'Use effective strategies, including spelling patterns, visual memory, mnemonics',
        'Use paper-based and on-screen tools to find correct spellings',
      ],
    },
    {
      id: 'english-3-writing-composition',
      name: 'Writing Composition',
      strand: 'Writing',
      codes: [
        '3Wv.01', '3Wv.02', '3Wv.03', '3Wv.04', '3Wv.05', '3Wv.06', '3Wv.07',
        '3Ws.01', '3Ws.02', '3Ws.03', '3Ws.04',
        '3Wc.01', '3Wc.02', '3Wc.03', '3Wc.04', '3Wc.05', '3Wc.06',
        '3Wp.01', '3Wp.02', '3Wp.03', '3Wp.04', '3Wp.05',
      ],
      objectives: [
        'Use specialised vocabulary accurately',
        'Explore and use synonyms for high-frequency words',
        'Explore and use different verbs for introducing and concluding dialogue',
        'Use varied sentence openings including time, place and manner',
        'Choose and use words and phrases (including noun phrases) to strengthen impact',
        'Use simple figurative language, including sound effects and simple onomatopoeia',
        'Use own lists of interesting and significant words, dictionaries and thesauruses',
        'Write a logical sequence of events or ideas',
        'Begin organising similar ideas in paragraphs or sections',
        'Use sentence openings that establish links between ideas',
        'Use organisational features appropriate to the text type',
        'Develop creative writing in a range of different genres of fiction and types of poems',
        'Plan and record main points and ideas before writing',
        'Develop setting and character descriptions in stories',
        'Write simple playscripts from narratives',
        'Develop writing for a purpose using language and features appropriate for a range of text types',
        'Develop writing of a range of text types for a specified audience',
        'Begin to write legibly and fluently',
        'Complete tables and diagrams recording information',
        'Explore and use different ways of laying out and presenting texts',
        'Evaluate own and others\' writing, suggesting improvements',
        'Proofread for grammar, spelling and punctuation errors, and make corrections',
      ],
    },
    {
      id: 'english-3-speaking-listening',
      name: 'Speaking and Listening',
      strand: 'Speaking and Listening',
      codes: [
        '3SLm.01', '3SLm.02', '3SLm.03', '3SLm.04', '3SLm.05',
        '3SLs.01', '3SLs.02',
        '3SLg.01', '3SLg.02', '3SLg.03', '3SLg.04',
        '3SLp.01', '3SLp.02', '3SLp.03', '3SLp.04', '3SLp.05',
        '3SLr.01', '3SLr.02',
      ],
      objectives: [
        'Speak fluently and confidently',
        'Select appropriate information with detail',
        'Use situation-appropriate vocabulary',
        'Use non-verbal communication',
        'Show audience awareness',
        'Listen and respond, following instruction sequences',
        'Ask questions that demonstrate understanding',
        'Begin taking assigned group roles',
        'Respond politely with viewpoints',
        'Extend discussions',
        'Take turns, acknowledge contributions',
        'Read aloud with expression',
        'Show awareness of different voices',
        'Use punctuation and grammar knowledge when reading aloud',
        'Use speech, gesture and movement for characters',
        'Plan and deliver independent presentations',
        'Begin to evaluate own and others\' talk',
        'Comment on verbal and non-verbal meaning',
      ],
    },
  ],
  4: [
    {
      id: 'english-4-reading-comprehension',
      name: 'Reading Comprehension',
      strand: 'Reading',
      codes: [
        '4Rw.01', '4Rw.02', '4Rw.03',
        '4Rs.01', '4Rs.02', '4Rs.03', '4Rs.04',
        '4Ri.01', '4Ri.02', '4Ri.03', '4Ri.04', '4Ri.05', '4Ri.06', '4Ri.07',
        '4Ri.08', '4Ri.09', '4Ri.10', '4Ri.11', '4Ri.12', '4Ri.13', '4Ri.14',
        '4Ri.15', '4Ri.16', '4Ri.17',
        '4Ra.01', '4Ra.02', '4Ra.03', '4Ra.04',
      ],
      objectives: [
        'Use effective strategies to read unfamiliar words accurately and confidently',
        'Identify stressed and unstressed syllables',
        'Extend the range of common words recognised on sight',
        'Explore text stages from introduction to conclusion',
        'Recognise key structural features across fiction and non-fiction',
        'Explore paragraph and section organisation',
        'Recognise point sequencing and linking',
        'Classify fiction and non-fiction',
        'Read and explore fiction genres, poems, playscripts',
        'Compare genre characteristics',
        'Read and explore non-fiction text types',
        'Compare non-fiction purposes and features',
        'Explore explicit and implicit meanings',
        'Identify key words establishing main points',
        'Explain settings and characters',
        'Predict story events',
        'Make inferences about settings and characters',
        'Distinguish fact from opinion',
        'Skim texts for key information',
        'Locate and use relevant information',
        'Answer questions with text references',
        'Compare and contrast themes and features',
        'Identify story viewpoint',
        'Enjoy independent and shared reading',
        'Express personal responses linking characters, settings and events',
        'Develop book preferences and recommendations',
        'Comment on how fiction reflects time and context',
      ],
    },
    {
      id: 'english-4-vocabulary',
      name: 'Vocabulary',
      strand: 'Reading',
      codes: [
        '4Rv.01', '4Rv.02', '4Rv.03', '4Rv.04',
        '4Rv.05', '4Rv.06', '4Rv.07', '4Rv.08',
      ],
      objectives: [
        'Use context to suggest synonyms',
        'Explore words with common roots',
        'Identify and record interesting and significant words, and synonyms, from texts',
        'Use as many initial letters as necessary to organise words in alphabetical order',
        'Explore and comment on how a writer\'s choice of words, including verbs, strengthens impact',
        'Explore and comment on how adjectives and adverbs enhance meaning',
        'Identify and recognise meaning of figurative language including alliteration and similes',
        'Comment on the impact of figurative language in texts',
      ],
    },
    {
      id: 'english-4-grammar-punctuation',
      name: 'Grammar and Punctuation',
      strand: 'Writing',
      codes: [
        '4Rg.01', '4Rg.02', '4Rg.03', '4Rg.04', '4Rg.05',
        '4Rg.06', '4Rg.07', '4Rg.08', '4Rg.09', '4Rg.10',
        '4Wg.01', '4Wg.02', '4Wg.03', '4Wg.04', '4Wg.05',
        '4Wg.06', '4Wg.07', '4Wg.08', '4Wg.09', '4Wg.10',
      ],
      objectives: [
        'Use knowledge of punctuation and grammar to read unfamiliar texts with understanding',
        'Explore and understand use of commas and apostrophes',
        'Explore and understand standard layout and punctuation of direct speech',
        'Explore different connectives in multi-clause sentences',
        'Identify connectives in texts',
        'Explore quantifier examples',
        'Explore adverbs and adverbial phrases, including their purposes',
        'Identify adverbs in texts',
        'Explore and understand how past, present and future verb forms are used',
        'Explore and understand subject-verb agreement',
        'Consistently use accurate end-of-sentence punctuation',
        'Begin using commas to clarify meaning',
        'Use apostrophes for possession',
        'Begin to use other punctuation alongside speech marks to punctuate direct speech',
        'Write multi-clause sentences using a range of connectives',
        'Use verb forms accurately',
        'Experiment with varying verb forms in texts, including in direct speech',
        'Use "to be" accurately including subject-verb agreement',
        'Use quantifiers appropriately',
        'Use adverbs and adverbial phrases appropriately',
      ],
    },
    {
      id: 'english-4-spelling',
      name: 'Spelling',
      strand: 'Writing',
      codes: [
        '4Ww.01', '4Ww.02', '4Ww.03', '4Ww.04', '4Ww.05',
        '4Ww.06', '4Ww.07', '4Ww.08', '4Ww.09',
      ],
      objectives: [
        'Explore and use silent letters and different spellings of words with vowel phonemes',
        'Explore and use spelling patterns for pluralisation',
        'Spell words with a range of common prefixes and suffixes',
        'Explore and build words with related roots and meanings',
        'Spell common homophones correctly to match their grammatical purpose',
        'Spell words with common letter strings but different pronunciations',
        'Generate and test spelling rules',
        'Use effective strategies including segmenting, spelling rules, visual memory',
        'Use paper-based and on-screen tools for correct spelling',
      ],
    },
    {
      id: 'english-4-writing-composition',
      name: 'Writing Composition',
      strand: 'Writing',
      codes: [
        '4Wv.01', '4Wv.02', '4Wv.03', '4Wv.04', '4Wv.05', '4Wv.06',
        '4Ws.01', '4Ws.02', '4Ws.03', '4Ws.04',
        '4Wc.01', '4Wc.02', '4Wc.03', '4Wc.04', '4Wc.05',
        '4Wc.06', '4Wc.07', '4Wc.08', '4Wc.09', '4Wc.10',
        '4Wp.01', '4Wp.02', '4Wp.03', '4Wp.04', '4Wp.05',
      ],
      objectives: [
        'Use specialised vocabulary accurately',
        'Explore alternatives for overused words and phrases',
        'Explore shades of meaning in adjectives and adverbs',
        'Choose and use words (including verbs) to strengthen writing impact',
        'Use figurative language including alliteration and similes',
        'Use own lists of interesting words, dictionaries and thesauruses',
        'Develop logical idea sequences',
        'Use paragraphs and sections consistently',
        'Use connectives to link paragraphs',
        'Use text-type appropriate organisational features',
        'Develop creative writing across genres',
        'Explore and use different planning approaches',
        'Write character profiles',
        'Develop descriptions to capture imagination',
        'Write alternative story beginnings and endings',
        'Begin to express viewpoint through character opinions',
        'Write simple original playscripts',
        'Develop purposeful writing',
        'Develop audience-appropriate writing',
        'Adopt viewpoints in non-fiction',
        'Write legibly, fluently and with increasing speed',
        'Make short notes',
        'Explore presentation and layout',
        'Evaluate own and others\' writing',
        'Proofread for errors',
      ],
    },
    {
      id: 'english-4-speaking-listening',
      name: 'Speaking and Listening',
      strand: 'Speaking and Listening',
      codes: [
        '4SLm.01', '4SLm.02', '4SLm.03', '4SLm.04', '4SLm.05',
        '4SLs.01',
        '4SLg.01', '4SLg.02', '4SLg.03', '4SLg.04',
        '4SLp.01', '4SLp.02', '4SLp.03', '4SLp.04',
        '4SLr.01', '4SLr.02',
      ],
      objectives: [
        'Speak with accuracy and sometimes at length',
        'Sequence information',
        'Use vocabulary precisely',
        'Use non-verbal communication',
        'Show audience awareness',
        'Listen and respond appropriately, including asking and answering questions',
        'Begin taking assigned group roles',
        'Respond politely with viewpoints',
        'Extend discussions',
        'Take turns, make links',
        'Read aloud adapting pace and volume',
        'Read with accuracy and fluency showing punctuation awareness',
        'Adapt speech, gesture and movement for drama',
        'Plan and deliver group presentations',
        'Begin to evaluate own and others\' talk',
        'Comment on verbal and non-verbal meaning expression',
      ],
    },
  ],
  5: [
    {
      id: 'english-5-reading-comprehension',
      name: 'Reading Comprehension',
      strand: 'Reading',
      codes: [
        '5Rw.01', '5Rw.02', '5Rw.03',
        '5Rs.01', '5Rs.02', '5Rs.03', '5Rs.04',
        '5Ri.01', '5Ri.02', '5Ri.03', '5Ri.04', '5Ri.05', '5Ri.06', '5Ri.07',
        '5Ri.08', '5Ri.09', '5Ri.10', '5Ri.11', '5Ri.12', '5Ri.13', '5Ri.14',
        '5Ri.15', '5Ri.16', '5Ri.17',
        '5Ra.01', '5Ra.02', '5Ra.03', '5Ra.04',
      ],
      objectives: [
        'Use multiple effective strategies for unfamiliar words',
        'Identify stressed and unstressed syllables in complex words',
        'Extend sight word recognition including homophones',
        'Explore text structure stages',
        'Explore key structural features across genres',
        'Explore paragraph and section organisation',
        'Explore point sequencing and linking',
        'Classify fiction and non-fiction',
        'Read and explore fiction genres',
        'Compare genre characteristics',
        'Read and explore non-fiction',
        'Compare non-fiction purposes and features',
        'Explore explicit and implicit meanings',
        'Identify key words and main points',
        'Explain character and setting development',
        'Predict story progression',
        'Make character and setting inferences',
        'Distinguish fact from opinion',
        'Skim texts for key information',
        'Locate and use information',
        'Answer questions referencing text points',
        'Compare and contrast themes',
        'Identify story viewpoint',
        'Enjoy independent reading across genres',
        'Express personal responses',
        'Develop preferences and recommendations',
        'Comment on historical and contextual reflection',
      ],
    },
    {
      id: 'english-5-vocabulary',
      name: 'Vocabulary',
      strand: 'Reading',
      codes: [
        '5Rv.01', '5Rv.02', '5Rv.03', '5Rv.04',
        '5Rv.05', '5Rv.06', '5Rv.07', '5Rv.08',
      ],
      objectives: [
        'Use context for synonyms',
        'Explore common root words',
        'Identify and record significant words',
        'Organise words alphabetically for dictionaries and glossaries',
        'Analyse writer\'s word choices including verbs',
        'Analyse adjectives and adverbs enhancing meaning',
        'Identify figurative language including metaphor and personification',
        'Comment on figurative language impact',
      ],
    },
    {
      id: 'english-5-grammar-punctuation',
      name: 'Grammar and Punctuation',
      strand: 'Writing',
      codes: [
        '5Rg.01', '5Rg.02', '5Rg.03', '5Rg.04', '5Rg.05',
        '5Rg.06', '5Rg.07', '5Rg.08', '5Rg.09', '5Rg.10',
        '5Wg.01', '5Wg.02', '5Wg.03', '5Wg.04', '5Wg.05',
        '5Wg.06', '5Wg.07', '5Wg.08', '5Wg.09', '5Wg.10',
      ],
      objectives: [
        'Use punctuation and grammar knowledge for unfamiliar texts',
        'Explore comma and apostrophe usage',
        'Understand direct speech layout and punctuation',
        'Explore connectives in complex sentences',
        'Identify connectives',
        'Explore quantifiers',
        'Explore adverbs and adverbial phrases',
        'Identify adverbs',
        'Understand verb tenses',
        'Understand subject-verb agreement',
        'Consistently use accurate sentence punctuation',
        'Use commas effectively',
        'Use apostrophes for possession',
        'Use speech punctuation accurately',
        'Write multi-clause sentences with connectives',
        'Use verb forms accurately',
        'Experiment with varying verb forms',
        'Use "to be" accurately',
        'Use quantifiers appropriately',
        'Use adverbial phrases effectively',
      ],
    },
    {
      id: 'english-5-spelling',
      name: 'Spelling',
      strand: 'Writing',
      codes: [
        '5Ww.01', '5Ww.02', '5Ww.03', '5Ww.04', '5Ww.05',
        '5Ww.06', '5Ww.07', '5Ww.08', '5Ww.09',
      ],
      objectives: [
        'Explore silent letters and vowel patterns',
        'Use spelling patterns for varied pluralisation',
        'Spell words with extensive prefixes and suffixes',
        'Build words with related roots',
        'Spell homophones matching grammatical purpose',
        'Spell letter string variations',
        'Generate and apply spelling rules',
        'Use multiple effective spelling strategies',
        'Use digital and print tools for spelling',
      ],
    },
    {
      id: 'english-5-writing-composition',
      name: 'Writing Composition',
      strand: 'Writing',
      codes: [
        '5Wv.01', '5Wv.02', '5Wv.03', '5Wv.04', '5Wv.05', '5Wv.06',
        '5Ws.01', '5Ws.02', '5Ws.03', '5Ws.04',
        '5Wc.01', '5Wc.02', '5Wc.03', '5Wc.04', '5Wc.05',
        '5Wc.06', '5Wc.07', '5Wc.08', '5Wc.09', '5Wc.10',
        '5Wp.01', '5Wp.02', '5Wp.03', '5Wp.04', '5Wp.05',
      ],
      objectives: [
        'Use specialised vocabulary',
        'Explore alternatives for overused expressions',
        'Explore adjective and adverb shades of meaning',
        'Use words strengthening impact',
        'Use figurative language including metaphor and personification',
        'Use reference sources',
        'Develop logical idea sequences',
        'Use paragraphs and sections effectively',
        'Use connectives linking paragraphs',
        'Use text-type appropriate organisational features',
        'Develop creative writing across genres',
        'Explore and use varied planning approaches',
        'Write character profiles',
        'Develop character and setting descriptions',
        'Write alternative story versions',
        'Express viewpoint through characters',
        'Write original playscripts',
        'Develop purposeful writing',
        'Develop audience-appropriate writing',
        'Adopt viewpoints in non-fiction',
        'Write legibly, fluently and speedily',
        'Make notes from reading',
        'Explore presentation and layout',
        'Evaluate own and others\' writing',
        'Proofread for errors',
      ],
    },
    {
      id: 'english-5-speaking-listening',
      name: 'Speaking and Listening',
      strand: 'Speaking and Listening',
      codes: [
        '5SLm.01', '5SLm.02', '5SLm.03', '5SLm.04', '5SLm.05',
        '5SLs.01',
        '5SLg.01', '5SLg.02', '5SLg.03', '5SLg.04',
        '5SLp.01', '5SLp.02', '5SLp.03', '5SLp.04',
        '5SLr.01', '5SLr.02',
      ],
      objectives: [
        'Speak accurately and extensively',
        'Sequence information clearly',
        'Use precise vocabulary',
        'Use non-verbal communication',
        'Show audience awareness',
        'Listen and respond appropriately to ideas',
        'Take assigned group roles',
        'Respond with viewpoints',
        'Extend discussions relevantly',
        'Make discussion links',
        'Read aloud with adapted expression and pace',
        'Read with accuracy and fluency',
        'Adapt speech, gesture and movement for drama',
        'Plan and deliver group presentations',
        'Evaluate own and others\' talk',
        'Comment on meaning expression',
      ],
    },
  ],
  6: [
    {
      id: 'english-6-reading-comprehension',
      name: 'Reading Comprehension',
      strand: 'Reading',
      codes: [
        '6Rw.01', '6Rw.02', '6Rw.03',
        '6Rs.01', '6Rs.02', '6Rs.03', '6Rs.04',
        '6Ri.01', '6Ri.02', '6Ri.03', '6Ri.04', '6Ri.05', '6Ri.06', '6Ri.07',
        '6Ri.08', '6Ri.09', '6Ri.10', '6Ri.11', '6Ri.12', '6Ri.13', '6Ri.14',
        '6Ri.15', '6Ri.16', '6Ri.17',
        '6Ra.01', '6Ra.02', '6Ra.03', '6Ra.04',
      ],
      objectives: [
        'Apply comprehensive strategies for complex unfamiliar words',
        'Identify syllable stress in multisyllabic words',
        'Extend sight word recognition',
        'Analyse text organisational stages',
        'Analyse key structural features',
        'Analyse organisational patterns',
        'Analyse point sequencing',
        'Classify fiction and non-fiction',
        'Explore multiple genres and formats',
        'Compare genre characteristics',
        'Explore varied non-fiction',
        'Compare non-fiction features',
        'Explore explicit and implicit meanings',
        'Identify key establishing points',
        'Explain complex character and setting development',
        'Predict complex outcomes',
        'Make sophisticated inferences',
        'Distinguish fact from opinion',
        'Skim comprehensively',
        'Locate relevant information',
        'Answer with textual references',
        'Compare themes across texts',
        'Analyse narrative viewpoint',
        'Enjoy sophisticated independent reading',
        'Express detailed personal responses',
        'Articulate developed preferences',
        'Analyse historical and contextual connections',
      ],
    },
    {
      id: 'english-6-vocabulary',
      name: 'Vocabulary',
      strand: 'Reading',
      codes: [
        '6Rv.01', '6Rv.02', '6Rv.03', '6Rv.04',
        '6Rv.05', '6Rv.06', '6Rv.07', '6Rv.08',
      ],
      objectives: [
        'Deduce synonyms from context',
        'Explore related root word meanings',
        'Record significant words and synonyms',
        'Alphabetically organise words',
        'Analyse word choices strengthening impact',
        'Analyse adjectives and adverbs for meaning',
        'Identify complex figurative language',
        'Analyse figurative language effects',
      ],
    },
    {
      id: 'english-6-grammar-punctuation',
      name: 'Grammar and Punctuation',
      strand: 'Writing',
      codes: [
        '6Rg.01', '6Rg.02', '6Rg.03', '6Rg.04', '6Rg.05',
        '6Rg.06', '6Rg.07', '6Rg.08', '6Rg.09', '6Rg.10',
        '6Wg.01', '6Wg.02', '6Wg.03', '6Wg.04', '6Wg.05',
        '6Wg.06', '6Wg.07', '6Wg.08', '6Wg.09', '6Wg.10',
      ],
      objectives: [
        'Use grammar and punctuation knowledge comprehensively',
        'Understand punctuation use across text types',
        'Understand speech conventions',
        'Explore connectives in complex sentences',
        'Identify connectives',
        'Explore quantifier usage',
        'Explore adverbial purposes',
        'Identify adverbs',
        'Understand verb tense usage',
        'Understand subject-verb agreement',
        'Use consistent sentence punctuation',
        'Use commas effectively',
        'Use possessive apostrophes',
        'Use speech punctuation accurately',
        'Write complex connected sentences',
        'Use accurate verb forms',
        'Experiment with verb variations',
        'Use "to be" accurately',
        'Use quantifiers appropriately',
        'Use adverbial phrases effectively',
      ],
    },
    {
      id: 'english-6-spelling',
      name: 'Spelling',
      strand: 'Writing',
      codes: [
        '6Ww.01', '6Ww.02', '6Ww.03', '6Ww.04', '6Ww.05',
        '6Ww.06', '6Ww.07', '6Ww.08', '6Ww.09',
      ],
      objectives: [
        'Apply silent letter and vowel patterns',
        'Apply pluralisation patterns',
        'Spell complex prefix and suffix words',
        'Build words with related meanings',
        'Spell grammatically accurate homophones',
        'Spell variable pronunciations',
        'Apply and test spelling rules',
        'Use comprehensive spelling strategies',
        'Use digital and print tools for spelling',
      ],
    },
    {
      id: 'english-6-writing-composition',
      name: 'Writing Composition',
      strand: 'Writing',
      codes: [
        '6Wv.01', '6Wv.02', '6Wv.03', '6Wv.04', '6Wv.05', '6Wv.06',
        '6Ws.01', '6Ws.02', '6Ws.03', '6Ws.04',
        '6Wc.01', '6Wc.02', '6Wc.03', '6Wc.04', '6Wc.05',
        '6Wc.06', '6Wc.07', '6Wc.08', '6Wc.09', '6Wc.10',
        '6Wp.01', '6Wp.02', '6Wp.03', '6Wp.04', '6Wp.05',
      ],
      objectives: [
        'Use specialised vocabulary',
        'Explore expression alternatives',
        'Apply adjective and adverb meaning variations',
        'Use powerful word choices',
        'Use sophisticated figurative language',
        'Use reference sources',
        'Develop complex idea sequences',
        'Organise with paragraphs and sections',
        'Link paragraphs with connectives',
        'Use appropriate organisational features',
        'Develop sophisticated creative writing',
        'Use complex planning strategies',
        'Create detailed character profiles',
        'Develop sophisticated descriptions',
        'Write varied story versions',
        'Express nuanced viewpoints',
        'Write complex playscripts',
        'Develop varied purposeful writing',
        'Develop audience-appropriate texts',
        'Adopt sophisticated non-fiction viewpoints',
        'Write legibly, fluently and quickly',
        'Use notes strategically',
        'Use varied presentation methods',
        'Provide sophisticated evaluation',
        'Proofread comprehensively',
      ],
    },
    {
      id: 'english-6-speaking-listening',
      name: 'Speaking and Listening',
      strand: 'Speaking and Listening',
      codes: [
        '6SLm.01', '6SLm.02', '6SLm.03', '6SLm.04', '6SLm.05',
        '6SLs.01',
        '6SLg.01', '6SLg.02', '6SLg.03', '6SLg.04',
        '6SLp.01', '6SLp.02', '6SLp.03', '6SLp.04',
        '6SLr.01', '6SLr.02',
      ],
      objectives: [
        'Speak with accuracy, length and sophistication',
        'Sequence information clearly',
        'Use precise vocabulary',
        'Use non-verbal communication effectively',
        'Show audience awareness',
        'Listen and respond developing understanding',
        'Take meaningful group roles',
        'Respond with considered viewpoints',
        'Contribute substantively to discussions',
        'Make sophisticated discussion links',
        'Read with sophisticated expression',
        'Read with fluency and punctuation awareness',
        'Portray complex drama characters',
        'Deliver sophisticated presentations',
        'Provide sophisticated talk evaluation',
        'Analyse meaning expression methods',
      ],
    },
  ],
};

module.exports = english;
