// curriculum-maths.js
// Source: Cambridge Primary Mathematics Framework 0845
// https://cambridgeinternational.org/programmes-and-qualifications/cambridge-primary/curriculum/mathematics/

const maths = {
  1: [
    {
      id: 'maths-1-counting',
      name: 'Counting and Place Value',
      strand: 'Number',
      codes: ['1Nn1', '1Nn2', '1Nn3', '1Nn4', '1Nn5', '1Nn6', '1Nn7', '1Nn8', '1Nn9', '1Nn10', '1Nn11', '1Nn12'],
      objectives: [
        'Recite numbers in order (at least to 100)',
        'Read and write numerals 0 to 20',
        'Count objects reliably',
        'Understand counting conservation',
        'Count on in twos and tens',
        'Begin to count on in fives',
        'Even numbers as every other number',
        'Partition two-digit numbers into tens and ones',
        'Compare two-digit numbers using > and <',
        'Order numbers to at least 20',
        'Understand and use ordinal numbers',
        'Use the = sign to represent equality',
        'Estimate a quantity by giving a range of numbers',
      ],
    },
    {
      id: 'maths-1-add-sub',
      name: 'Addition and Subtraction',
      strand: 'Number',
      codes: ['1Nc1', '1Nc2', '1Nc3', '1Nc4', '1Nc5', '1Nc6', '1Nc7', '1Nc8', '1Nc9', '1Nc10', '1Nc11', '1Nc12', '1Nc13', '1Nc14', '1Nc15', '1Nc16', '1Nc17', '1Nc18'],
      objectives: [
        'Know all number pairs to 10 and pairs with a total of 6, 7, 8, 9, 10',
        'Add more than two small numbers',
        'Begin bridging through 10',
        'Know doubles to at least double 5',
        'Identify near doubles',
        'Begin to know multiplication facts for 2x and 10x tables',
        'Understand addition as combining groups and counting on',
        'Understand subtraction as counting back, taking away, and finding a difference',
        'Record addition and subtraction sentences',
        'Know that addition can be done in any order (commutativity)',
        'Add and subtract single-digit numbers to and from two-digit numbers',
      ],
    },
    {
      id: 'maths-1-mult-div',
      name: 'Multiplication and Division',
      strand: 'Number',
      codes: ['1Nc19', '1Nc20', '1Nc21', '1Nc22'],
      objectives: [
        'Double single-digit numbers',
        'Halve even numbers to 10',
        'Share objects into equal groups',
        'Find simple remainders after division',
      ],
    },
    {
      id: 'maths-1-fractions',
      name: 'Fractions',
      strand: 'Number',
      codes: [],
      objectives: [],
    },
    {
      id: 'maths-1-shapes',
      name: 'Shapes and Geometry',
      strand: 'Geometry',
      codes: ['1Gs1', '1Gs2', '1Gs3'],
      objectives: [
        'Name and sort common 2D shapes (circles, squares, rectangles, triangles)',
        'Identify 3D shapes (cubes, cuboids, cylinders, spheres, cones, pyramids) and describe properties',
        'Recognise basic line symmetry',
      ],
    },
    {
      id: 'maths-1-position',
      name: 'Position and Movement',
      strand: 'Geometry',
      codes: ['1Gp1'],
      objectives: [
        'Use language of direction and distance (left, right, up, down, forwards, backwards)',
      ],
    },
    {
      id: 'maths-1-money',
      name: 'Money',
      strand: 'Measure',
      codes: ['1Mm1'],
      objectives: [
        'Recognise all coins and notes',
        'Use money to pay for items using exact amounts',
      ],
    },
    {
      id: 'maths-1-length',
      name: 'Length, Mass and Capacity',
      strand: 'Measure',
      codes: ['1Ml1', '1Ml2', '1Ml3'],
      objectives: [
        'Compare lengths, masses, and capacities by direct comparison',
        'Estimate and measure using non-standard units',
        'Use comparative language (longer, shorter, heavier, lighter, more, less)',
      ],
    },
    {
      id: 'maths-1-time',
      name: 'Time',
      strand: 'Measure',
      codes: ['1Mt1', '1Mt2', '1Mt3'],
      objectives: [
        'Know units of time (seconds, minutes, hours, days, weeks, months, years)',
        'Read analogue clocks to the hour (o\'clock)',
        'Order the days of the week',
      ],
    },
    {
      id: 'maths-1-data',
      name: 'Data Handling',
      strand: 'Handling Data',
      codes: ['1Dh1'],
      objectives: [
        'Answer a question by sorting and organising data in block graphs, pictograms, lists, tables, Venn and Carroll diagrams',
      ],
    },
  ],
  2: [
    {
      id: 'maths-2-counting',
      name: 'Counting and Place Value',
      strand: 'Number',
      codes: ['2Nn1', '2Nn2', '2Nn3', '2Nn4', '2Nn5', '2Nn6', '2Nn7', '2Nn8', '2Nn9', '2Nn10', '2Nn11', '2Nn12', '2Nn13', '2Nn14', '2Nn15', '2Nn16', '2Nn17', '2Nn18', '2Nn19'],
      objectives: [
        'Read and write numbers to at least 100',
        'Count objects (groups of tens and ones)',
        'Count on and back in ones, tens, twos, and fives',
        'Partition two-digit numbers',
        'Find 1 or 10 more or less than a number',
        'Round two-digit numbers to nearest 10',
        'Use ordinal numbers',
        'Compare and order numbers to 100',
        'Estimate quantities',
        'Recognise odd and even numbers',
        'Understand fraction notation (halves and quarters)',
        'Find halves and quarters of shapes and small numbers',
        'Recognise equivalence between 1/2 and 2/4',
      ],
    },
    {
      id: 'maths-2-add-sub',
      name: 'Addition and Subtraction',
      strand: 'Number',
      codes: ['2Nc1', '2Nc2', '2Nc3', '2Nc4', '2Nc5', '2Nc6', '2Nc7', '2Nc8', '2Nc9', '2Nc10', '2Nc11', '2Nc12', '2Nc13', '2Nc14', '2Nc15'],
      objectives: [
        'Know pairs that total 10 and 20',
        'Partition to 20',
        'Pairs of multiples of 10 totalling 100',
        'Begin to know multiplication facts for 2x, 5x, 10x tables',
        'Know doubles to at least 20',
        'Count on and back in tens from two-digit numbers',
        'Represent equality',
        'Add 4 or 5 small numbers',
        'Find unknown in number sentences (e.g. [] + 3 = 10)',
        'Add and subtract single-digit to and from two-digit numbers',
        'Add pairs of two-digit numbers',
        'Find differences by counting up',
      ],
    },
    {
      id: 'maths-2-mult-div',
      name: 'Multiplication and Division',
      strand: 'Number',
      codes: ['2Nc16', '2Nc17', '2Nc18', '2Nc19', '2Nc20', '2Nc21', '2Nc22', '2Nc23'],
      objectives: [
        'Understand multiplication as repeated addition and arrays',
        'Understand division as grouping and sharing',
        'Double multiples of 5 to 50',
        'Double two-digit numbers',
        'Begin to learn 3x and 4x tables',
        'Understand remainders in division',
      ],
    },
    {
      id: 'maths-2-fractions',
      name: 'Fractions',
      strand: 'Number',
      codes: [],
      objectives: [
        'Understand fraction notation (halves and quarters)',
        'Find halves and quarters of shapes and small numbers',
        'Recognise equivalence between 1/2 and 2/4',
      ],
    },
    {
      id: 'maths-2-shapes',
      name: 'Shapes and Geometry',
      strand: 'Geometry',
      codes: ['2Gs1', '2Gs2', '2Gs3', '2Gs4'],
      objectives: [
        'Sort, name, describe, and draw 2D shapes (squares, rectangles, circles, triangles, pentagons, hexagons)',
        'Identify properties of 3D shapes',
        'Find reflective symmetry in patterns and shapes',
        'Identify shapes in the environment',
      ],
    },
    {
      id: 'maths-2-position',
      name: 'Position and Movement',
      strand: 'Geometry',
      codes: ['2Gp1', '2Gp2', '2Gp3'],
      objectives: [
        'Follow and give instructions for position, direction, and movement',
        'Understand whole, half, and quarter turns',
        'Recognise right angles in turns',
      ],
    },
    {
      id: 'maths-2-money',
      name: 'Money',
      strand: 'Measure',
      codes: ['2Mm1', '2Mm2', '2Mm3'],
      objectives: [
        'Recognise all coins and notes',
        'Use money notation',
        'Find totals and give change',
      ],
    },
    {
      id: 'maths-2-length',
      name: 'Length, Mass and Capacity',
      strand: 'Measure',
      codes: ['2Ml1', '2Ml2'],
      objectives: [
        'Estimate, measure, and compare lengths, masses, and capacities using standard units (cm, m, 100g, kg, litre)',
      ],
    },
    {
      id: 'maths-2-time',
      name: 'Time',
      strand: 'Measure',
      codes: ['2Mt1', '2Mt2', '2Mt3', '2Mt4', '2Mt5'],
      objectives: [
        'Know time units and relationships between them',
        'Read clocks to the half hour',
        'Measure activities in seconds and minutes',
        'Order months of the year and days of the week',
      ],
    },
    {
      id: 'maths-2-data',
      name: 'Data Handling',
      strand: 'Handling Data',
      codes: ['2Dh1', '2Dh2'],
      objectives: [
        'Collect and organise data in lists, tables, block graphs, pictograms, Carroll and Venn diagrams',
        'Use one and two criteria for sorting',
      ],
    },
  ],
  3: [
    {
      id: 'maths-3-counting',
      name: 'Counting and Place Value',
      strand: 'Number',
      codes: ['3Nn1', '3Nn2', '3Nn3', '3Nn4', '3Nn5', '3Nn6', '3Nn7', '3Nn8', '3Nn9', '3Nn10', '3Nn11', '3Nn12', '3Nn13', '3Nn14', '3Nn15', '3Nn16', '3Nn17', '3Nn18', '3Nn19', '3Nn20'],
      objectives: [
        'Recite numbers 100 to 200 and beyond',
        'Read and write numbers to 1000',
        'Count in ones, tens, hundreds',
        'Count in steps of 2, 3, 4, and 5',
        'Understand place value in three-digit numbers',
        'Find 1, 10, or 100 more or less',
        'Multiply single-digit numbers by 10',
        'Round two-digit numbers to nearest 10 and three-digit numbers to nearest 100',
        'Place numbers on a number line',
        'Compare and order three-digit numbers',
        'Estimate by approximation',
      ],
    },
    {
      id: 'maths-3-add-sub',
      name: 'Addition and Subtraction',
      strand: 'Number',
      codes: ['3Nc1', '3Nc2', '3Nc3', '3Nc4', '3Nc5', '3Nc6', '3Nc7', '3Nc8', '3Nc9', '3Nc10', '3Nc11', '3Nc12', '3Nc13', '3Nc14', '3Nc15', '3Nc16', '3Nc17', '3Nc18'],
      objectives: [
        'Know addition and subtraction facts to 20',
        'Add and subtract multiples of 100 to 1000',
        'Know 2x, 3x, 5x, 10x tables',
        'Begin 4x table',
        'Recognise multiples of 2, 5, 10',
        'Know doubles to 20 and doubles of multiples of 10',
        'Add and subtract 10 and multiples of 10',
        'Add 100 to three-digit numbers',
        'Add several small numbers',
        'Find complements to 100',
        'Add and subtract pairs of two-digit numbers',
        'Add three-digit and two-digit numbers',
        'Reorder additions',
        'Add and subtract near multiples of 10',
        'Find 20, 30 ... 100, 200, 300 more or less',
      ],
    },
    {
      id: 'maths-3-mult-div',
      name: 'Multiplication and Division',
      strand: 'Number',
      codes: ['3Nc19', '3Nc20', '3Nc21', '3Nc22', '3Nc23', '3Nc24', '3Nc25', '3Nc26'],
      objectives: [
        'Understand relationship between halving and doubling',
        'Multiply two-digit numbers by 10',
        'Multiply and divide by 2, 3, 4, 5, 6, 9, 10',
        'Understand remainders',
        'Know commutativity of multiplication',
        'Understand multiplication and division relationship',
      ],
    },
    {
      id: 'maths-3-fractions',
      name: 'Fractions',
      strand: 'Number',
      codes: [],
      objectives: [
        'Understand halves of odd and even numbers',
        'Use fraction notation (3/4 as three quarters)',
        'Recognise equivalences (1/2 = 2/4 = 4/8 = 5/10)',
        'Understand mixed numbers',
        'Order unit fractions',
        'Understand fraction as division',
        'Find halves, thirds, quarters, and tenths of shapes and numbers',
      ],
    },
    {
      id: 'maths-3-shapes',
      name: 'Shapes and Geometry',
      strand: 'Geometry',
      codes: ['3Gs1', '3Gs2', '3Gs3', '3Gs4', '3Gs5', '3Gs6', '3Gs7', '3Gs8'],
      objectives: [
        'Identify and describe regular and irregular 2D shapes including pentagons, hexagons, octagons, semi-circles',
        'Classify by properties (sides, vertices, right angles)',
        'Identify 3D shapes including pyramids and prisms',
        'Explore cube nets',
        'Identify 2D shapes with reflective symmetry',
        'Create reflections using mirror lines',
        'Relate 2D and 3D shapes to drawings',
        'Identify right angles in 2D shapes',
      ],
    },
    {
      id: 'maths-3-position',
      name: 'Position and Movement',
      strand: 'Geometry',
      codes: ['3Gp1', '3Gp2', '3Gp3', '3Gp4'],
      objectives: [
        'Use direction and movement language (clockwise, anti-clockwise)',
        'Read and use grid positions with labelled rows and columns',
        'Draw and compare angles to right angles',
        'Understand a straight line equals two right angles',
      ],
    },
    {
      id: 'maths-3-money',
      name: 'Money',
      strand: 'Measure',
      codes: ['3Mm1', '3Mm2'],
      objectives: [
        'Consolidate money notation',
        'Calculate change using complements to 100',
      ],
    },
    {
      id: 'maths-3-length',
      name: 'Length, Mass and Capacity',
      strand: 'Measure',
      codes: ['3Ml1', '3Ml2', '3Ml3', '3Ml4', '3Ml5'],
      objectives: [
        'Choose appropriate units and equipment',
        'Know relationships (km/m, m/cm, kg/g, l/ml)',
        'Read scales to nearest division',
        'Measure with ruler to nearest cm',
        'Solve word problems involving measures',
      ],
    },
    {
      id: 'maths-3-time',
      name: 'Time',
      strand: 'Measure',
      codes: ['3Mt1', '3Mt2', '3Mt3', '3Mt4'],
      objectives: [
        'Choose time units and know relationships',
        'Read analogue clocks to nearest 5 minutes and digital clocks to nearest minute',
        'Calculate simple time intervals',
        'Use calendars and calculate week and day intervals',
      ],
    },
    {
      id: 'maths-3-data',
      name: 'Data Handling',
      strand: 'Handling Data',
      codes: ['3Dh1', '3Dh2', '3Dh3'],
      objectives: [
        'Investigate real-life questions with data collection, organisation, and interpretation',
        'Use tally charts, frequency tables, pictograms (1-2 unit symbols), bar charts',
        'Use Venn and Carroll diagrams with two criteria',
      ],
    },
  ],
  4: [
    {
      id: 'maths-4-counting',
      name: 'Counting and Place Value',
      strand: 'Number',
      codes: ['4Nn1', '4Nn2', '4Nn3', '4Nn4', '4Nn5', '4Nn6', '4Nn7', '4Nn8', '4Nn9', '4Nn10', '4Nn11', '4Nn12', '4Nn13', '4Nn14', '4Nn15', '4Nn16', '4Nn17', '4Nn18', '4Nn19', '4Nn20', '4Nn21', '4Nn22', '4Nn23', '4Nn24', '4Nn25'],
      objectives: [
        'Read and write numbers to 10,000',
        'Count in various steps including thousands',
        'Use decimal notation for tenths and hundredths (money and length contexts)',
        'Find multiples of 10, 100, 1000 more or less',
        'Multiply and divide by 10 and begin by 100',
        'Recognise multiples',
        'Round 3-4 digit numbers',
        'Use empty number lines',
        'Estimate',
        'Understand negative numbers in context',
        'Recognise number sequences',
        'Explore odd and even properties',
        'Make general statements about odd and even sums and differences',
      ],
    },
    {
      id: 'maths-4-add-sub',
      name: 'Addition and Subtraction',
      strand: 'Number',
      codes: ['4Nc1', '4Nc2', '4Nc3', '4Nc4', '4Nc5', '4Nc6', '4Nc7', '4Nc8', '4Nc9', '4Nc10', '4Nc11', '4Nc12', '4Nc13', '4Nc14', '4Nc15', '4Nc16', '4Nc17', '4Nc18', '4Nc19'],
      objectives: [
        'Know pairs of two-digit numbers totalling 100',
        'Pairs of multiples of 50 totalling 1000',
        'Simple fraction pairs totalling 1',
        'Know all tables to 10x10',
        'Add 3 or 4 small numbers',
        'Add three two-digit multiples of 10',
        'Add and subtract near multiples of 10 or 100',
        'Add and subtract pairs of two-digit numbers',
        'Find differences between near multiples of 100',
        'Multiply single-digit pairs',
        'Use commutativity',
        'Understand effect of multiplying by 10',
        'Know doubles to 50, 500, 5000 and corresponding halves',
        'Add pairs of three-digit numbers',
        'Subtract two-digit from three-digit',
        'Subtract pairs of three-digit numbers',
      ],
    },
    {
      id: 'maths-4-mult-div',
      name: 'Multiplication and Division',
      strand: 'Number',
      codes: ['4Nc20', '4Nc21', '4Nc22', '4Nc23', '4Nc24', '4Nc25', '4Nc26'],
      objectives: [
        'Double two-digit numbers',
        'Multiply multiples of 10 (10-90)',
        'Multiply two-digit by single-digit',
        'Divide two-digit by single-digit (answers up to 20)',
        'Understand rounding after division',
        'Use multiplication and division as inverses',
        'Introduce simple ratio and proportion',
      ],
    },
    {
      id: 'maths-4-fractions',
      name: 'Fractions and Decimals',
      strand: 'Number',
      codes: [],
      objectives: [
        'Order fractions with same denominator',
        'Understand fraction equivalences (1/2 = 4/8 = 5/10, 1/4 = 2/8, 1/5 = 2/10)',
        'Use equivalences for ordering',
        'Understand decimal and fraction equivalence (0.5 = 1/2 = 5/10)',
        'Recognise mixed numbers (e.g. 5 3/4)',
        'Understand fraction and division relationship',
        'Find halves, quarters, thirds, fifths, eighths, tenths of shapes and numbers',
      ],
    },
    {
      id: 'maths-4-shapes',
      name: 'Shapes and Geometry',
      strand: 'Geometry',
      codes: ['4Gs1', '4Gs2', '4Gs3', '4Gs4', '4Gs5'],
      objectives: [
        'Identify wider range of 2D and 3D shapes (quadrilaterals, heptagons, tetrahedra)',
        'Use pinboards and spotty paper',
        'Classify polygons (right angles, regularity, symmetry)',
        'Identify lines of reflective symmetry',
        'Visualise 3D from 2D nets and drawings',
        'Identify common solid nets',
        'Find shapes and symmetry in the environment and art',
      ],
    },
    {
      id: 'maths-4-position',
      name: 'Position and Movement',
      strand: 'Geometry',
      codes: ['4Gp1', '4Gp2', '4Gp3'],
      objectives: [
        'Read and describe grid positions (numbered and lettered rows and columns)',
        'Measure angles in degrees (360 degrees = full turn, 4 right angles = 360 degrees)',
        'Compare and order angles less than 180 degrees',
        'Describe paths and directions',
      ],
    },
    {
      id: 'maths-4-money',
      name: 'Money',
      strand: 'Measure',
      codes: [],
      objectives: [
        'Use decimal notation for money',
        'Solve problems involving money in real-life contexts',
      ],
    },
    {
      id: 'maths-4-length',
      name: 'Length, Mass and Capacity',
      strand: 'Measure',
      codes: ['4Ml1', '4Ml2', '4Ml3', '4Ml4'],
      objectives: [
        'Use standard metric units with abbreviations (km, m, cm, mm, kg, g, l, ml)',
        'Know relationships between familiar units',
        'Understand kilo, centi, milli prefixes',
        'Use decimal notation for measures (1.3 m, 0.6 kg, 1.2 l)',
        'Interpret partially numbered scales',
      ],
    },
    {
      id: 'maths-4-time',
      name: 'Time',
      strand: 'Measure',
      codes: ['4Mt1', '4Mt2', '4Mt3', '4Mt4'],
      objectives: [
        'Read time to nearest minute (12-hour digital and analogue)',
        'Use a.m. and p.m. notation',
        'Read simple timetables',
        'Use calendars',
        'Choose appropriate time units',
      ],
    },
    {
      id: 'maths-4-area',
      name: 'Area and Perimeter',
      strand: 'Measure',
      codes: ['4Ma1', '4Ma2', '4Ma3'],
      objectives: [
        'Measure and calculate rectangle perimeters',
        'Understand area measured in square units (cm squared)',
        'Find areas of rectilinear shapes by counting squares',
      ],
    },
    {
      id: 'maths-4-data',
      name: 'Data Handling',
      strand: 'Handling Data',
      codes: ['4Dh1', '4Dh2', '4Dh3'],
      objectives: [
        'Identify data to collect',
        'Organise and present data in tables, diagrams, tally charts, frequency tables, pictograms (2/5/10/20 unit symbols), bar charts',
        'Compare impact of different scale intervals',
        'Use Venn and Carroll diagrams with two to three criteria',
      ],
    },
  ],
  5: [
    {
      id: 'maths-5-counting',
      name: 'Counting and Place Value',
      strand: 'Number',
      codes: ['5Nn1', '5Nn2', '5Nn3', '5Nn4', '5Nn5', '5Nn6', '5Nn7', '5Nn8', '5Nn9', '5Nn10', '5Nn11', '5Nn12', '5Nn13', '5Nn14', '5Nn15', '5Nn16', '5Nn17', '5Nn18', '5Nn19', '5Nn20', '5Nn21', '5Nn22'],
      objectives: [
        'Count forwards and backwards through zero',
        'Understand place value in 5-6 digit numbers',
        'Partition numbers to one million',
        'Use decimal notation for tenths and hundredths with place value understanding',
        'Multiply and divide numbers 1-10,000 by 10 and 100',
        'Round 4-digit numbers to nearest 10, 100, 1000',
        'Round one to two decimal place numbers',
        'Order and compare numbers to one million',
        'Order positive and negative numbers',
        'Understand temperature rise and fall',
        'Order and compare numbers with one to two decimal places',
        'Recognise and extend number sequences',
        'Understand odd and even and multiples (5, 10, 25, 50, 100) to 1000',
        'Make general statements about odd and even sums, differences, and multiples',
      ],
    },
    {
      id: 'maths-5-add-sub',
      name: 'Addition and Subtraction',
      strand: 'Number',
      codes: ['5Nc1', '5Nc2', '5Nc3', '5Nc4', '5Nc5', '5Nc6', '5Nc7', '5Nc8', '5Nc9', '5Nc10', '5Nc11', '5Nc12', '5Nc13', '5Nc14', '5Nc15', '5Nc16', '5Nc17', '5Nc18', '5Nc19'],
      objectives: [
        'Know pairs of one-place decimals totalling 1 and 10',
        'Know all tables to 10x10',
        'Test divisibility by 2, 5, 10, 100',
        'Know multiples of 6-9',
        'Know square numbers to 10x10',
        'Identify two-digit factors',
        'Count on and back through thousands, hundreds, tens, ones',
        'Add and subtract near multiples of 10 and 100',
        'Strategies for two to three digit numbers with one decimal place',
        'Find differences near 1000 and near 1',
        'Multiply multiples of 10-90 and 100-900',
        'Multiply by 19 or 21 (via 20)',
        'Multiply by 25 (via 100 divided by 4)',
        'Use factor multiplication',
        'Double to 100 and 200',
        'Double and halve one to two decimal numbers',
        'Double and halve multiples of 10-1000',
        'Find totals of 3 or more two to three digit numbers',
        'Add and subtract three to four digit numbers with same decimal places (including money)',
      ],
    },
    {
      id: 'maths-5-mult-div',
      name: 'Multiplication and Division',
      strand: 'Number',
      codes: ['5Nc20', '5Nc21', '5Nc22', '5Nc23', '5Nc24', '5Nc25', '5Nc26', '5Nc27'],
      objectives: [
        'Multiply and divide three-digit by single-digit',
        'Multiply two-digit by two-digit',
        'Multiply one decimal place numbers by two-digit',
        'Divide three-digit by single-digit with remainders (answers up to 30)',
        'Express remainder as fraction of divisor',
        'Decide when to group or share in division',
        'Round division answers context-dependently',
        'Use brackets for operation ordering',
        'Understand four operations relationships and arithmetic laws',
      ],
    },
    {
      id: 'maths-5-fractions',
      name: 'Fractions, Decimals and Percentages',
      strand: 'Number',
      codes: [],
      objectives: [
        'Understand fraction equivalences (1/2, 1/4, 1/8 and 1/3, 1/6 and 1/5, 1/10)',
        'Compare decimals and fractions',
        'Convert improper fractions to mixed numbers (e.g. 7/4 = 1 3/4)',
        'Order mixed numbers',
        'Understand fraction and division relationship',
        'Find fractions of quantities',
        'Understand percentages as parts of 100',
        'Calculate simple percentages',
        'Express halves, tenths, hundredths as percentages',
        'Use fractions for proportion',
        'Use ratio for problem solving (e.g. recipe adaptation)',
      ],
    },
    {
      id: 'maths-5-shapes',
      name: 'Shapes and Geometry',
      strand: 'Geometry',
      codes: ['5Gs1', '5Gs2', '5Gs3', '5Gs4', '5Gs5', '5Gs6', '5Gs7'],
      objectives: [
        'Classify triangles (isosceles, equilateral, scalene)',
        'Identify regular polygon symmetry (reflective and rotational)',
        'Create patterns with two lines of symmetry',
        'Visualise 3D shapes from 2D nets (cube variants)',
        'Identify perpendicular and parallel lines',
        'Measure angles in degrees (nearest 5 degrees)',
        'Classify angles as acute, right, or obtuse',
        'Know angles on a straight line',
      ],
    },
    {
      id: 'maths-5-position',
      name: 'Position and Movement',
      strand: 'Geometry',
      codes: ['5Gp1', '5Gp2', '5Gp3'],
      objectives: [
        'Read and plot co-ordinates in first quadrant',
        'Predict reflections (mirror parallel to side, including oblique lines)',
        'Understand and predict translations',
        'Give translation instructions',
      ],
    },
    {
      id: 'maths-5-length',
      name: 'Length, Mass and Capacity',
      strand: 'Measure',
      codes: ['5Ml1', '5Ml2', '5Ml3', '5Ml4', '5Ml5', '5Ml6', '5Ml7'],
      objectives: [
        'Read and select standard units with suitable accuracy',
        'Convert larger to smaller metric units (using decimals to one place)',
        'Order mixed units',
        'Round to nearest whole unit',
        'Interpret unnumbered scale divisions',
        'Compare readings from different scales',
        'Measure and draw lines in cm and mm',
      ],
    },
    {
      id: 'maths-5-time',
      name: 'Time',
      strand: 'Measure',
      codes: ['5Mt1', '5Mt2', '5Mt3', '5Mt4', '5Mt5', '5Mt6'],
      objectives: [
        'Know time units (seconds through years)',
        'Compare 24-hour digital and analogue clocks',
        'Read 24-hour timetables',
        'Calculate time intervals (seconds, minutes, hours)',
        'Calculate calendar day and week intervals',
        'Calculate month and year intervals',
      ],
    },
    {
      id: 'maths-5-area',
      name: 'Area and Perimeter',
      strand: 'Measure',
      codes: ['5Ma1', '5Ma2', '5Ma3'],
      objectives: [
        'Measure and calculate perimeters of regular and irregular polygons',
        'Understand area in square centimetres',
        'Calculate rectangle areas using formula (length x width)',
      ],
    },
    {
      id: 'maths-5-data',
      name: 'Data Handling',
      strand: 'Handling Data',
      codes: ['5Dh1', '5Dh2', '5Dh3', '5Dh4', '5Dh5'],
      objectives: [
        'Develop question sets with data collection, selection, and organisation',
        'Draw conclusions from data',
        'Identify further questions',
        'Interpret frequency tables, pictograms, bar line charts (various vertical axis scales)',
        'Understand vertical axis scale impact',
        'Interpret simple line graphs (e.g. temperature over time)',
        'Understand intermediate point meaning',
        'Identify and interpret the mode',
      ],
    },
    {
      id: 'maths-5-probability',
      name: 'Probability',
      strand: 'Handling Data',
      codes: ['5Db1'],
      objectives: [
        'Use language of chance and likelihood to describe familiar events',
      ],
    },
  ],
  6: [
    {
      id: 'maths-6-counting',
      name: 'Counting and Place Value',
      strand: 'Number',
      codes: ['6Nn1', '6Nn2', '6Nn3', '6Nn4', '6Nn5', '6Nn6', '6Nn7', '6Nn8', '6Nn9', '6Nn10', '6Nn11', '6Nn12', '6Nn13', '6Nn14', '6Nn15', '6Nn16', '6Nn17', '6Nn18', '6Nn19', '6Nn20', '6Nn21', '6Nn22', '6Nn23', '6Nn24', '6Nn25', '6Nn26', '6Nn27', '6Nn28', '6Nn29', '6Nn30'],
      objectives: [
        'Count in fractions, decimals, and whole numbers (including through zero)',
        'Understand place value to one million',
        'Represent one to two decimal places',
        'Multiply and divide 1-10,000 by 10, 100, 1000',
        'Multiply and divide decimals by 10 and 100',
        'Find two-digit factors',
        'Find common multiples',
        'Round whole numbers to 10, 100, 1000',
        'Round two decimal places to nearest tenth or whole',
        'Estimate and justify large numbers',
        'Order and compare to one million and negative integers',
        'Use >, <, = correctly',
        'Estimate on 0-10,000 number lines',
        'Order numbers with up to two decimal places (varying places)',
        'Recognise and extend sequences',
        'Understand three decimal place decimals in measurement contexts',
        'Identify odd and even, multiples, and prime numbers to 20 and less than 100',
        'Explore number system origins and development',
      ],
    },
    {
      id: 'maths-6-add-sub',
      name: 'Addition and Subtraction',
      strand: 'Number',
      codes: ['6Nc1', '6Nc2', '6Nc3', '6Nc4', '6Nc5', '6Nc6', '6Nc7', '6Nc8', '6Nc9', '6Nc10', '6Nc11', '6Nc12', '6Nc13'],
      objectives: [
        'Know addition and subtraction facts within 20',
        'One-place decimal pairs totalling 1',
        'One-place decimal pairs totalling 10',
        'Two-place decimal pairs totalling 1',
        'Test divisibility (2, 4, 5, 10, 25, 100)',
        'Add and subtract two-digit wholes and three-digit multiples of 10',
        'Add and subtract decimal pairs (e.g. 2.6 + 2.7, 0.78 + 0.23)',
        'Adjust near multiples of 10, 100, 1000',
        'Use place value and multiplication facts for mental division and multiplication (0.8 x 7, 4.8 / 6)',
        'Multiply pairs of multiples of 10 (30 x 40, 600 x 40)',
        'Double two-digit numbers (78, 7.8, 0.78) and find halves',
        'Divide two-digit by single-digit mentally',
        'Add and subtract two to three digit numbers with same or different decimal places including money',
        'Find differences between positive and negative integers',
        'Find differences between two negative integers (temperature and number line contexts)',
      ],
    },
    {
      id: 'maths-6-mult-div',
      name: 'Multiplication and Division',
      strand: 'Number',
      codes: ['6Nc14', '6Nc15', '6Nc16', '6Nc17', '6Nc18', '6Nc19', '6Nc20', '6Nc21', '6Nc22'],
      objectives: [
        'Multiply multiples of 10 pairs (30 x 40)',
        'Multiply 10 and 100 multiples (600 x 40)',
        'Adjust near 10 multiples',
        'Use halving-doubling (35 x 16 as 70 x 8)',
        'Generate new facts from known facts (17x from 10x + 7x)',
        'Multiply two to four digit by single-digit (including money)',
        'Multiply two to three digit by two-digit',
        'Divide three-digit by single-digit (with remainder)',
        'Divide three-digit by two-digit (no remainder, including money)',
        'Express division answers as mixed numbers and decimals',
        'Use fraction operators (tenths and hundredths of quantities)',
        'Apply commutativity, associativity, distributivity',
      ],
    },
    {
      id: 'maths-6-fractions',
      name: 'Fractions, Decimals and Percentages',
      strand: 'Number',
      codes: [],
      objectives: [
        'Compare fractions using denominators (3/4 with 7/8)',
        'Understand equivalences (1/100s, 1/10s, 1/2s)',
        'Convert improper fractions to mixed numbers (e.g. 17/8 = 2 1/8)',
        'Reduce fractions to simplest form',
        'Convert vulgar fractions to decimals via division',
        'Express percentages (1/2, 1/4, 1/3, 1/10, 1/100)',
        'Find simple percentages of shapes and whole numbers',
        'Solve simple ratio and proportion problems',
      ],
    },
    {
      id: 'maths-6-shapes',
      name: 'Shapes and Geometry',
      strand: 'Geometry',
      codes: ['6Gs1', '6Gs2', '6Gs3', '6Gs4', '6Gs5', '6Gs6'],
      objectives: [
        'Classify polygons and identify non-polygons',
        'Describe 3D shape properties (faces, edges, vertices)',
        'Classify quadrilaterals (parallelogram, rhombus, trapezium) by properties (parallel sides, equal sides and angles)',
        'Create 2D representations of 3D shapes including nets',
        'Estimate and measure angles with protractor (nearest degree)',
        'Understand triangle angle sum (180 degrees)',
        'Calculate angles in triangles and at points',
      ],
    },
    {
      id: 'maths-6-position',
      name: 'Position and Movement',
      strand: 'Geometry',
      codes: ['6Gp1', '6Gp2'],
      objectives: [
        'Read and plot co-ordinates in all four quadrants',
        'Predict reflections (including non-parallel and non-perpendicular sides to mirror)',
        'Predict translations',
        'Predict 90-degree rotations about a vertex',
      ],
    },
    {
      id: 'maths-6-length',
      name: 'Length, Mass and Capacity',
      strand: 'Measure',
      codes: ['6Ml1', '6Ml2', '6Ml3', '6Ml4', '6Ml5'],
      objectives: [
        'Select standard units with two to three decimal place reading',
        'Convert units (kg/g, l/ml, km/m/cm/mm) using three decimal places (e.g. 1.245 m = 1 m 24.5 cm)',
        'Interpret scales from range of instruments',
        'Measure and draw lines in cm and mm',
        'Know imperial units still in use (mile) and metric approximations',
      ],
    },
    {
      id: 'maths-6-time',
      name: 'Time',
      strand: 'Measure',
      codes: ['6Mt1', '6Mt2', '6Mt3', '6Mt4', '6Mt5', '6Mt6', '6Mt7', '6Mt8'],
      objectives: [
        'Understand time units (seconds through centuries) with conversions',
        'Use 24-hour digital and analogue clocks',
        'Compare 24-hour formats',
        'Read and use 24-hour timetables',
        'Calculate 24-hour time intervals',
        'Calculate calendar day, week, and month intervals',
        'Calculate month and year intervals',
        'Understand time zone differences worldwide',
      ],
    },
    {
      id: 'maths-6-area',
      name: 'Area and Perimeter',
      strand: 'Measure',
      codes: ['6Ma1', '6Ma2', '6Ma3'],
      objectives: [
        'Measure and calculate perimeters and areas of rectilinear shapes',
        'Estimate irregular shape areas (square counting)',
        'Calculate compound shape perimeters and areas (rectangular split)',
      ],
    },
    {
      id: 'maths-6-data',
      name: 'Data Handling',
      strand: 'Handling Data',
      codes: ['6Dh1', '6Dh2', '6Dh3', '6Dh4'],
      objectives: [
        'Represent, extract, and interpret data from tables, graphs, charts, diagrams including line graphs (distance-time), price ready-reckoners, frequency tables, grouped discrete bar charts',
        'Identify mode and range',
        'Begin to understand median and mean',
        'Explore everyday statistics',
      ],
    },
    {
      id: 'maths-6-probability',
      name: 'Probability',
      strand: 'Handling Data',
      codes: ['6Db1'],
      objectives: [
        'Use probability language',
        'Assess likelihood and risk',
        'Identify events with equally likely outcomes',
      ],
    },
  ],
};

module.exports = maths;
