// curriculum-arabic.js
// Source: Egyptian Ministry of Education — Arabic Language Curriculum 2025-2026
// Egyptian Education 2.0 Reform (نظام التعليم الجديد 2.0)
// Textbooks: المكتبة الإلكترونية — ellibrary.moe.gov.eg/books/

const arabic = {
  1: [
    {
      id: 'arabic-1-letters',
      name: 'Arabic Alphabet — الحروف العربية',
      strand: 'Reading',
      codes: [],
      objectives: [
        'Recognise and name all 28 Arabic letters',
        'Identify letter forms: initial, medial, final, isolated',
        'Match each letter to its sound (letter-sound correspondence)',
        'Read and write letters: أ، ب، م، هـ، ج، د، خ، ط (Unit 1 set)',
        'Read and write letters: ل، س، ن، ر، ف، ك، ق (Unit 2 set)',
        'Read and write letters: ي، ع، ش، و، ح، ذ، ظ (Unit 3 set)',
        'Consolidate remaining letters in Unit 4',
      ],
    },
    {
      id: 'arabic-1-phonics',
      name: 'Short Vowels and Phonics — الحركات',
      strand: 'Reading',
      codes: [],
      objectives: [
        'Identify and pronounce the three short vowels: فتحة، ضمة، كسرة',
        'Read simple 3-letter (CVC) words with short vowels',
        'Develop phonemic awareness through songs and listening',
        'Blend letter sounds to decode simple words',
      ],
    },
    {
      id: 'arabic-1-family',
      name: 'My Family — أسرتي',
      strand: 'Listening & Speaking',
      codes: [],
      objectives: [
        'Listen to and comprehend the story "أميرة وأسرتها السعيدة" (Amira and Her Happy Family)',
        'Sing and recite the song "أسرتي" (My Family)',
        'Read the simple reader "أحب أسرتي" (I Love My Family)',
        'Use basic family vocabulary: أب، أم، أخ، أخت',
        'Speak about one\'s own family in simple sentences',
      ],
    },
    {
      id: 'arabic-1-animals',
      name: 'My Animals — حيواناتي',
      strand: 'Listening & Speaking',
      codes: [],
      objectives: [
        'Listen to and comprehend "عالم الحيوان" (The Animal World)',
        'Sing and recite "لوحتي الجديدة" (My New Painting)',
        'Read the simple reader "ماذا يأكلون؟" (What Do They Eat?)',
        'Participate in family reading: "التعاون سر النجاح" (Cooperation Is the Secret of Success)',
        'Name common animals and describe them orally',
      ],
    },
    {
      id: 'arabic-1-body',
      name: 'My Body — جسمي',
      strand: 'Listening & Speaking',
      codes: [],
      objectives: [
        'Listen to and comprehend "صندوق جدتي" (Grandma\'s Box)',
        'Sing and recite "أحب جسمي" (I Love My Body)',
        'Read the simple reader "هذا جسمي" (This Is My Body)',
        'Name basic body parts in Arabic',
        'Follow simple oral instructions involving body parts',
      ],
    },
    {
      id: 'arabic-1-writing',
      name: 'Handwriting and Dictation — النسخ والإملاء',
      strand: 'Writing',
      codes: [],
      objectives: [
        'Form Arabic letters correctly in isolation and connected forms (نسخ/خط)',
        'Copy simple words from a model',
        'Write learned letters and simple words from dictation',
        'Build oral vocabulary through songs (أناشيد) and stories',
      ],
    },
  ],

  2: [
    {
      id: 'arabic-2-reading',
      name: 'Fluent Reading — القراءة المتصلة',
      strand: 'Reading',
      codes: [],
      objectives: [
        'Read short connected texts with fluency and accuracy',
        'Read passages related to the theme "المعاملة الطيبة" (Kind Treatment)',
        'Read thematic texts from "كيف يعمل العالم" (How the World Works) and "التواصل" (Communication)',
        'Answer simple comprehension questions about read texts',
        'Recognise common sight words in context',
      ],
    },
    {
      id: 'arabic-2-vocabulary',
      name: 'Expanded Vocabulary — المفردات',
      strand: 'Reading',
      codes: [],
      objectives: [
        'Build vocabulary through diverse thematic units',
        'Use context clues to understand new words in texts',
        'Understand and use words related to interpersonal values and kindness',
        'Recognise the definite article (ال) in common words',
      ],
    },
    {
      id: 'arabic-2-writing',
      name: 'Basic Sentence Writing — كتابة الجمل',
      strand: 'Writing',
      codes: [],
      objectives: [
        'Write simple sentences independently',
        'Write short paragraphs of 2-3 sentences on a given topic',
        'Spell common words correctly in dictation exercises',
        'Use intuitive sentence patterns without formal grammar instruction',
      ],
    },
    {
      id: 'arabic-2-listening-speaking',
      name: 'Listening and Speaking — الاستماع والتحدث',
      strand: 'Listening & Speaking',
      codes: [],
      objectives: [
        'Listen to and retell simple stories and passages',
        'Present ideas orally in simple structured formats',
        'Participate in classroom discussions about unit themes',
        'Respond to questions about listened texts with appropriate detail',
      ],
    },
  ],

  3: [
    {
      id: 'arabic-3-reading',
      name: 'Reading Comprehension — القراءة والفهم',
      strand: 'Reading',
      codes: [],
      objectives: [
        'Read and comprehend passages from Unit 1 "العمل والأمل" (Work and Hope): "من فضلك.. كرر المحاولة" and "البطل الصامت"',
        'Read and comprehend passages from Unit 2 "صفاتي الجميلة" (My Beautiful Qualities): "السعادة في المساعدة" and "أول من يرفع يده"',
        'Read and comprehend passages from Unit 3 "أحب بلدي" (I Love My Country): "صندوق الابتكار" and "صفحة من التاريخ"',
        'Answer comprehension questions about reading passages',
        'Make predictions and inferences from text',
      ],
    },
    {
      id: 'arabic-3-listening',
      name: 'Listening Comprehension — الاستماع',
      strand: 'Listening & Speaking',
      codes: [],
      objectives: [
        'Listen to and comprehend "ازرع نبتة" (Plant a Seedling)',
        'Listen to and comprehend "الزهرة والصبار" (The Flower and the Cactus)',
        'Listen to and comprehend "العصفورة الشجاعة" (The Brave Sparrow)',
        'Respond orally to listened texts: "حاول مرة أخرى", "شكراً لك", "أساعد غيري", "أبادر"',
      ],
    },
    {
      id: 'arabic-3-interrogatives',
      name: 'Interrogative Particles — أدوات الاستفهام',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Recognise and use interrogative particles: من (who), ما (what), هل (does/is), لماذا (why)',
        'Form simple questions using أدوات الاستفهام (interrogative particles)',
        'Distinguish between different question types in reading passages',
      ],
    },
    {
      id: 'arabic-3-demonstratives',
      name: 'Demonstrative Pronouns — أسماء الإشارة',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Recognise and use demonstrative pronouns: هؤلاء (these — people), أولئك (those — people)',
        'Use demonstrative pronouns correctly in oral and written sentences',
      ],
    },
    {
      id: 'arabic-3-number',
      name: 'Singular, Dual, and Plural — المفرد والمثنى والجمع',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Distinguish between singular (المفرد), dual (المثنى), and plural (الجمع) noun forms',
        'Recognise singular, dual, and plural nouns in reading passages',
        'Convert simple nouns between singular, dual, and plural forms',
      ],
    },
    {
      id: 'arabic-3-negation',
      name: 'Negation — أدوات النفي',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Recognise and use negation particles: لم (did not — past), لن (will not — future)',
        'Form negative sentences using لم and لن in context',
      ],
    },
    {
      id: 'arabic-3-prepositions-conjunctions',
      name: 'Prepositions and Conjunctions — حروف الجر والعطف',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Recognise and use prepositions: عن (about), على (on/upon)',
        'Recognise and use conjunctions: ثم (then), فـ (and so/then)',
        'Use prepositions and conjunctions to connect ideas in sentences',
      ],
    },
    {
      id: 'arabic-3-poetry',
      name: 'Poetry Appreciation — النصوص الشعرية',
      strand: 'Reading',
      codes: [],
      objectives: [
        'Listen to, recite, and appreciate "أسرار النجاح" (Secrets of Success)',
        'Listen to, recite, and appreciate "قيمنا" (Our Values)',
        'Listen to, recite, and appreciate "النشيد الوطني" (National Anthem)',
        'Identify rhyme and rhythm in simple Arabic poetry',
      ],
    },
    {
      id: 'arabic-3-writing',
      name: 'Writing and Spelling — الكتابة والإملاء',
      strand: 'Writing',
      codes: [],
      objectives: [
        'Compose picture stories (قصة مصورة) from sequenced images',
        'Write alternative story endings based on reading passages',
        'Apply التنوين (tanween/nunation) correctly in spelling',
        'Distinguish between open taa (ت), closed taa (ة), and haa (ه) in spelling',
        'Segment words into phonetic units for dictation',
      ],
    },
  ],

  4: [
    {
      id: 'arabic-4-word-types',
      name: 'Word Types and Noun Markers — أنواع الكلمة وعلامات الاسم',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Classify words into three types: اسم (noun), فعل (verb), حرف (particle)',
        'Identify علامات الاسم (noun markers) that distinguish nouns from verbs and particles',
        'Distinguish المفرد (singular), المثنى (dual), and الجمع (plural) forms with formal markers',
        'Apply word-type classification to texts from Unit 1 "أنا وحلمي" (I and My Dream)',
      ],
    },
    {
      id: 'arabic-4-subject-predicate',
      name: 'Subject and Predicate — المبتدأ والخبر',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Identify the two components of الجملة الاسمية (nominal sentence): المبتدأ (subject) and الخبر (predicate)',
        'Recognise that المبتدأ والخبر are both مرفوع (in the nominative case)',
        'Construct correct nominal sentences with المبتدأ والخبر',
        'Analyse nominal sentences in texts from Unit 2 "أخلاقي.. حياتي" (My Ethics... My Life)',
        'Apply المبتدأ والخبر with المثنى (dual) and جمع المذكر السالم (masculine sound plural) from Unit 3',
      ],
    },
    {
      id: 'arabic-4-pronouns',
      name: 'Pronouns — الضمائر',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Identify and use Arabic personal pronouns (الضمائر المنفصلة)',
        'Use pronouns correctly as المبتدأ (subject) in nominal sentences',
        'Match pronouns with correct verb and predicate agreement',
      ],
    },
    {
      id: 'arabic-4-reading',
      name: 'Reading Comprehension — القراءة والفهم',
      strand: 'Reading',
      codes: [],
      objectives: [
        'Read and comprehend "صندوق الأحلام" (The Dream Box) and "من أنا؟" (Who Am I?)',
        'Read and comprehend "الغالي المجاني" (The Free Valuable Thing) and "فكر قليلاً.. تربح كثيراً" (Think Little, Win Much)',
        'Read and comprehend "رسالة الشجرة العجوز" (The Old Tree\'s Message) and "أفعال صغيرة ونتائج كبيرة" (Small Actions, Big Results)',
        'Participate in family reading (قراءة أسرية): "جسر الأمل", "الكلمة التي غيرت كل شيء", "درس لا يُنسى"',
        'Extract main ideas and supporting details from texts',
      ],
    },
    {
      id: 'arabic-4-listening',
      name: 'Listening and Speaking — الاستماع والتحدث',
      strand: 'Listening & Speaking',
      codes: [],
      objectives: [
        'Listen to and comprehend "كل منا له حلم" (Each of Us Has a Dream)',
        'Listen to and comprehend "قوة الأخلاق في حياتنا" (The Power of Ethics in Our Lives)',
        'Listen to and comprehend "رسالة إلى أصدقاء الطبيعة" (A Letter to Friends of Nature)',
        'Share personal aspirations orally with classmates',
        'Discuss emotions and ethical situations in structured speaking activities',
      ],
    },
    {
      id: 'arabic-4-poetry',
      name: 'Poetry — النصوص الشعرية',
      strand: 'Reading',
      codes: [],
      objectives: [
        'Recite and appreciate "اسلمي يا مصر" (Be Safe, O Egypt)',
        'Recite and appreciate "طريق السعادة" (The Road to Happiness)',
        'Recite and appreciate "في البستان" (In the Garden)',
        'Identify poetic imagery and emotional themes in verse',
      ],
    },
    {
      id: 'arabic-4-writing',
      name: 'Personal Letters and Creative Writing — الكتابة',
      strand: 'Writing',
      codes: [],
      objectives: [
        'Write a personal letter (رسالة شخصية) with greeting, body, and closing',
        'Compose structured paragraphs using concept mapping',
        'Write a letter addressed to nature with creative expression',
        'Apply punctuation marks (علامات الترقيم) correctly',
        'Spell words with preposition letters (ف، ب، ك، ل) joined to the definite article (ال)',
        'Identify حروف تُنطق ولا تُكتب (letters pronounced but not written)',
      ],
    },
  ],

  5: [
    {
      id: 'arabic-5-direct-object',
      name: 'Direct Object — المفعول به',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Identify المفعول به (direct object) in verbal sentences as a منصوب (accusative) element',
        'Apply المفعول به with المفرد (singular) and جمع التكسير (broken plural)',
        'Apply المفعول به with جمع المؤنث السالم (feminine sound plural)',
        'Analyse المفعول به in texts from Unit 1 "نيلنا أمانة" (Our Nile Is a Trust)',
        'Recognise case markers (علامات الإعراب) on the direct object including subsidiary markers (علامات فرعية)',
      ],
    },
    {
      id: 'arabic-5-subject-verbal',
      name: 'Subject of Verbal Sentence — الفاعل',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Identify الفاعل (subject) in verbal sentences as a مرفوع (nominative) element',
        'Distinguish between الفاعل in verbal sentences and المبتدأ in nominal sentences',
        'Analyse verbal sentences with both الفاعل and المفعول به',
        'Review and deepen understanding of المبتدأ والخبر (subject and predicate) from Grade 4',
      ],
    },
    {
      id: 'arabic-5-purpose-adverbs',
      name: 'Adverbial of Purpose and Time/Place Adverbs — المفعول لأجله وظرف الزمان والمكان',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Identify المفعول لأجله (adverbial accusative of purpose) in sentences',
        'Identify ظرف الزمان (time adverbs) and ظرف المكان (place adverbs)',
        'Apply correct إعراب (case marking) to ظرفي الزمان والمكان',
        'Use المفعول لأجله and ظروف correctly in written composition',
      ],
    },
    {
      id: 'arabic-5-relative-pronouns',
      name: 'Relative Pronouns — الأسماء الموصولة',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Identify and use الأسماء الموصولة (relative pronouns): الذي، التي، اللذان، اللتان، الذين، اللاتي',
        'Construct sentences using relative clauses with الأسماء الموصولة',
        'Recognise الأسماء الموصولة in reading passages and poetry',
      ],
    },
    {
      id: 'arabic-5-reading',
      name: 'Reading Comprehension — القراءة والفهم',
      strand: 'Reading',
      codes: [],
      objectives: [
        'Read and comprehend "لم ألوث ماء النهر" (I Did Not Pollute the River Water) and "بطل حل المشكلات" (Problem-Solving Hero)',
        'Read and comprehend "لغة النصر" (Language of Victory) and "الرسالة عبر الزمان" (Message Through Time)',
        'Participate in family reading: "لنحمِ نيلنا" (Let\'s Protect Our Nile)',
        'Identify main ideas, supporting details, and author\'s purpose in texts',
      ],
    },
    {
      id: 'arabic-5-listening',
      name: 'Listening and Speaking — الاستماع والتحدث',
      strand: 'Listening & Speaking',
      codes: [],
      objectives: [
        'Listen to and comprehend "سر الحياة" (Life\'s Secret)',
        'Listen to and comprehend "جسر التواصل" (Communication Bridge)',
        'Discuss the Nile and environmental responsibility in structured speaking',
        'Present on "سحر اللغات" (Magic of Languages) orally',
      ],
    },
    {
      id: 'arabic-5-poetry',
      name: 'Poetry — النصوص الشعرية',
      strand: 'Reading',
      codes: [],
      objectives: [
        'Recite and appreciate "حكاية عطاء" (Story of Giving)',
        'Recite and appreciate "أخي الإنسان" (My Human Brother)',
        'Analyse poetic language, imagery, and themes in assigned poems',
      ],
    },
    {
      id: 'arabic-5-writing',
      name: 'Formal Letters and Diary Writing — الكتابة',
      strand: 'Writing',
      codes: [],
      objectives: [
        'Write a formal letter (الرسالة الرسمية) with proper format and register',
        'Write personal diary entries (كتابة يوميات) reflecting on daily events',
        'Compose 2 written expression topics (موضوعات تعبير) per term',
        'Apply همزة القطع وألف الوصل (hamzat al-qat\' and alif al-wasl) correctly in spelling',
        'Apply الهمزة المتطرفة على السطر (final hamza on the line) correctly',
      ],
    },
  ],

  6: [
    {
      id: 'arabic-6-definite-indefinite',
      name: 'Indefinite and Definite — النكرة والمعرفة',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Distinguish between النكرة (indefinite) and المعرفة (definite) nouns',
        'Identify أنواع المعارف (types of definite nouns): proper nouns, pronouns, demonstratives, relative pronouns, nouns with ال, nouns in إضافة',
        'Classify nouns as نكرة or معرفة in texts from Unit 1 "أطور ذاتي" (I Develop Myself)',
      ],
    },
    {
      id: 'arabic-6-five-nouns',
      name: 'The Five Nouns — الأسماء الخمسة',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Identify الأسماء الخمسة: أبو، أخو، حمو، فو، ذو',
        'Apply their special case markers: الواو رفعاً (nominative), الألف نصباً (accusative), الياء جراً (genitive)',
        'Use الأسماء الخمسة correctly in written and oral sentences',
        'Analyse الأسماء الخمسة in texts from Unit 2 "أنا مسؤول" (I Am Responsible)',
      ],
    },
    {
      id: 'arabic-6-predicate-types',
      name: 'Types of Predicate — أنواع الخبر',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Identify الخبر المفرد (single-word predicate)',
        'Identify الخبر الجملة الاسمية (nominal sentence predicate)',
        'Identify الخبر الجملة الفعلية (verbal sentence predicate)',
        'Identify الخبر شبه الجملة (semi-sentence predicate: prepositional or adverbial phrase)',
        'Classify the predicate type in sentences and reading passages',
        'Construct sentences using each of the four predicate types',
      ],
    },
    {
      id: 'arabic-6-kana',
      name: 'Kana and Sisters — كان وأخواتها',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Identify كان وأخواتها (incomplete verbs that modify the nominal sentence)',
        'Recognise that كان raises المبتدأ to اسم كان (nominative) and changes الخبر to خبر كان (accusative)',
        'Apply أنواع خبر كان (types of predicate of كان) using the four predicate patterns',
        'Analyse sentences with كان وأخواتها in reading passages',
      ],
    },
    {
      id: 'arabic-6-inna',
      name: 'Inna and Sisters — إن وأخواتها',
      strand: 'Grammar',
      codes: [],
      objectives: [
        'Identify إن وأخواتها (emphatic particles that modify the nominal sentence)',
        'Recognise that إن changes المبتدأ to اسم إن (accusative) and keeps الخبر as خبر إن (nominative)',
        'Apply أنواع خبر إن (types of predicate of إن) using the four predicate patterns',
        'Contrast the effect of كان وأخواتها with إن وأخواتها on the nominal sentence (النواسخ)',
      ],
    },
    {
      id: 'arabic-6-reading',
      name: 'Reading Comprehension — القراءة والفهم',
      strand: 'Reading',
      codes: [],
      objectives: [
        'Read and comprehend "كنز لا يقدر بثمن" (A Priceless Treasure) and "اصنع قرارك" (Make Your Decision)',
        'Read and comprehend "قوة الكلمات" (The Power of Words) and "سر القوة والنجاح" (The Secret of Strength and Success)',
        'Engage with dramatic reading: play "فكر قبل أن تفعل" (Think Before You Act) — scenes 1 and 2',
        'Analyse author\'s purpose, tone, and argument in reading passages',
      ],
    },
    {
      id: 'arabic-6-listening',
      name: 'Listening and Speaking — الاستماع والتحدث',
      strand: 'Listening & Speaking',
      codes: [],
      objectives: [
        'Listen to and comprehend "سمر تطور نفسها" (Samar Develops Herself)',
        'Listen to and comprehend "من هم الناجحون" (Who Are the Successful?)',
        'Discuss "الوقت من ذهب" (Time Is Gold) and "أثر الكلمة" (Impact of Words) in structured speaking',
        'Present on "اصنع قرارك" and "كن مسئولاً" (Be Responsible) topics',
      ],
    },
    {
      id: 'arabic-6-poetry',
      name: 'Poetry — النصوص الشعرية',
      strand: 'Reading',
      codes: [],
      objectives: [
        'Recite and appreciate "إلى الشباب" (To the Youth)',
        'Recite and appreciate "بناة المجد" (Builders of Glory)',
        'Analyse poetic themes, imagery, rhetorical devices, and metre',
      ],
    },
    {
      id: 'arabic-6-writing',
      name: 'Essay and Report Writing — الكتابة',
      strand: 'Writing',
      codes: [],
      objectives: [
        'Write informational texts (نصوص معلوماتية) with clear structure and evidence',
        'Write reports (كتابة التقارير) with introduction, body, and conclusion',
        'Compose 2 written expression topics (موضوعات تعبير) per term',
        'Apply الهمزة المتوسطة على الألف (medial hamza on alif) correctly in spelling',
        'Apply الهمزة المتوسطة على الياء (medial hamza on ya) correctly in spelling',
      ],
    },
  ],
};

module.exports = arabic;
