// curriculum-science.js
// Source: Cambridge Primary Science Framework 0846
// https://cambridgeinternational.org/programmes-and-qualifications/cambridge-primary/curriculum/science/

const science = {
  1: [
    {
      id: 'science-1-plants',
      name: 'Plants and Living Things',
      strand: 'Biology',
      codes: ['1Bs.01', '1Bp.01', '1Bp.03', '1Bp1', '1Bp3'],
      objectives: [
        'Recognise and name the major parts of familiar flowering plants (root, stem, leaf, flower)',
        'Identify living things and things that have never been alive',
        'Know that plants need light and water to survive',
      ],
    },
    {
      id: 'science-1-animals',
      name: 'Animals and Humans',
      strand: 'Biology',
      codes: ['1Bs.02', '1Bs.03', '1Bp.02', '1Bp.04', '1Bp2', '1Bp4'],
      objectives: [
        'Identify the five senses, linking each to the correct body part',
        'Recognise and name the major external parts of the human body',
        'Know that animals, including humans, need air, water and suitable food',
        'Describe how humans are similar to and different from each other',
      ],
    },
    {
      id: 'science-1-materials',
      name: 'Materials and Their Properties',
      strand: 'Chemistry',
      codes: ['1Cm.01', '1Cm.02', '1Cm1', '1Cp.01', '1Cp.02', '1Cp1', '1Cp2', '1Cc.01'],
      objectives: [
        'Identify, name, describe, sort and group common materials, including wood, plastic, glass, rock, paper, fabric, metal, water, rubber',
        'Understand the difference between an object and a material',
        'Understand that all materials have a variety of properties (hard, soft, flexible, rigid, rough, smooth, shiny, dull)',
        'Describe common materials in terms of their properties',
        'Describe how materials can be changed by physical action (bending, stretching, squashing, twisting)',
      ],
    },
    {
      id: 'science-1-forces',
      name: 'Forces and Motion',
      strand: 'Physics',
      codes: ['1Pf.01', '1Pf.02', '1Pf.03', '1Pf1', '1Pf2', '1Pf3'],
      objectives: [
        'Explore, talk about and describe the movement of familiar objects',
        'Describe pushes and pulls as forces',
        'Explore that some objects float and some sink',
      ],
    },
    {
      id: 'science-1-light-sound',
      name: 'Light and Sound',
      strand: 'Physics',
      codes: ['1Ps.01', '1Ps.02', '1Ps1', '1Ps2'],
      objectives: [
        'Identify different sources of sound',
        'Explore that as sound travels from a source it becomes quieter',
      ],
    },
    {
      id: 'science-1-electricity',
      name: 'Electricity and Magnetism',
      strand: 'Physics',
      codes: ['1Pe.01', '1Pe.02'],
      objectives: [
        'Identify things that require electricity to work',
        'Explore what happens when magnets approach and touch different materials',
      ],
    },
    {
      id: 'science-1-enquiry',
      name: 'Scientific Enquiry',
      strand: 'Scientific Enquiry',
      codes: ['1Ep1', '1Ep2', '1Eo1', '1Eo2'],
      objectives: [
        'Explore and observe to find answers to questions',
        'Make predictions about what will happen',
        'Observe and compare objects, living things and events',
        'Record observations using drawings and simple tables',
      ],
    },
  ],
  2: [
    {
      id: 'science-2-plants',
      name: 'Plants and Living Things',
      strand: 'Biology',
      codes: ['2Bs1', '2Bs2', '2Bs3'],
      objectives: [
        'Know that plants produce seeds that grow into new plants',
        'Know that there is a variety of plants and animals',
        'Sort living things into groups using simple features and justify groupings',
      ],
    },
    {
      id: 'science-2-animals',
      name: 'Animals and Humans',
      strand: 'Biology',
      codes: ['2Bp1', '2Bp2', '2Bp3', '2Bp4'],
      objectives: [
        'Know the basic life processes common to humans and animals (nutrition, movement, growth, reproduction)',
        'Describe differences between living and non-living things using knowledge of life processes',
        'Identify different habitats and know that different animals are found in different habitats',
        'Explore how animals are adapted to their habitats',
      ],
    },
    {
      id: 'science-2-materials',
      name: 'Materials and Their Properties',
      strand: 'Chemistry',
      codes: ['2Cm1', '2Cp1', '2Cp2', '2Cc1', '2Cc2'],
      objectives: [
        'Know that every material has specific properties including hardness, strength, flexibility, and transparency',
        'Sort materials according to their properties',
        'Explore how some materials change when heated or cooled',
        'Describe how the shapes of some materials can be changed by squashing, bending, twisting, stretching',
        'Explore that some changes are reversible and some are not',
      ],
    },
    {
      id: 'science-2-forces',
      name: 'Forces and Motion',
      strand: 'Physics',
      codes: ['2Pf1'],
      objectives: [
        'Identify and explore how forces can make objects start or stop moving',
      ],
    },
    {
      id: 'science-2-light-sound',
      name: 'Light and Sound',
      strand: 'Physics',
      codes: ['2Pl1', '2Pl2', '2Pl3'],
      objectives: [
        'Know that darkness is the absence of light',
        'Identify light sources including the Sun and know that the Sun is a dangerous source of light',
        'Explore how shadows are formed and identify shadows',
      ],
    },
    {
      id: 'science-2-electricity',
      name: 'Electricity and Magnetism',
      strand: 'Physics',
      codes: ['2Pm1', '2Pm2'],
      objectives: [
        'Recognise the components of simple circuits involving cells (batteries), wires, bulbs/LEDs, motors, buzzers',
        'Construct simple series circuits',
      ],
    },
    {
      id: 'science-2-earth',
      name: 'Earth and Space',
      strand: 'Earth and Space',
      codes: ['2ES1', '2ES2'],
      objectives: [
        'Know that the Earth spins on its axis and this causes day and night',
        'Know that the Sun appears to move across the sky during the day',
      ],
    },
    {
      id: 'science-2-enquiry',
      name: 'Scientific Enquiry',
      strand: 'Scientific Enquiry',
      codes: ['2Ep1', '2Ep2', '2Ep3', '2Eo1', '2Eo2', '2Eo3', '2Eo4', '2Eo5'],
      objectives: [
        'Collect evidence by making observations when trying to answer a science question',
        'Suggest ideas and make predictions',
        'With guidance, begin to plan fair test investigations',
        'Observe and compare objects and events',
        'Measure and record observations using simple equipment',
        'Present results in drawings, tables, and block graphs',
        'Draw conclusions from results',
        'Identify simple patterns in results',
      ],
    },
  ],
  3: [
    {
      id: 'science-3-plants',
      name: 'Plants and Living Things',
      strand: 'Biology',
      codes: ['3Bp1', '3Bp2', '3Bp3', '3Bp4', '3Bp5'],
      objectives: [
        'Know that plants have roots, leaves, stems, and flowers',
        'Explain observations that plants need water and light to grow',
        'Know that water is taken in through the roots and transported through the stem',
        'Know that plants need healthy roots, leaves, and stems to grow well',
        'Know that plant growth is affected by temperature',
      ],
    },
    {
      id: 'science-3-animals',
      name: 'Animals and Humans',
      strand: 'Biology',
      codes: ['3Bh1', '3Bh2', '3Bh6'],
      objectives: [
        'Know life processes common to humans and animals include nutrition, movement, growth, and reproduction',
        'Describe differences between living and non-living things using life processes knowledge',
        'Sort living things into groups using simple features and justify groupings',
      ],
    },
    {
      id: 'science-3-materials',
      name: 'Materials and Their Properties',
      strand: 'Chemistry',
      codes: ['3Cp1', '3Cp2', '3Cp3', '3Cp4'],
      objectives: [
        'Know that every material has specific properties (hard, soft, shiny, etc.)',
        'Sort materials according to their properties',
        'Explore how some materials are magnetic, but many are not',
        'Discuss why materials are chosen for specific purposes based on their properties',
      ],
    },
    {
      id: 'science-3-forces',
      name: 'Forces and Motion',
      strand: 'Physics',
      codes: ['3Pf1', '3Pf2', '3Pf3', '3Pf4'],
      objectives: [
        'Know that pushes and pulls are examples of forces and that forces can be measured with forcemeters',
        'Explore how forces can make objects start moving, stop moving, speed up, or slow down',
        'Explore how forces can change the shape of objects',
        'Explore how forces including friction affect the movement of objects',
      ],
    },
    {
      id: 'science-3-enquiry',
      name: 'Scientific Enquiry',
      strand: 'Scientific Enquiry',
      codes: ['3Ep1', '3Ep2', '3Ep3', '3Eo1', '3Eo2', '3Eo3', '3Eo4', '3Eo5'],
      objectives: [
        'Collect evidence in a variety of contexts to answer questions or test ideas',
        'Suggest ideas, make predictions and communicate these',
        'With help, think about collecting evidence and planning fair tests',
        'Observe and compare living things and events',
        'Measure using simple equipment and record observations in a variety of ways',
        'Present results in drawings',
        'Draw conclusions from results and begin to use scientific knowledge to suggest explanations',
        'Make generalisations and identify simple patterns in results',
      ],
    },
  ],
  4: [
    {
      id: 'science-4-plants',
      name: 'Plants and Living Things',
      strand: 'Biology',
      codes: ['4Bp3', '4Bp4', '4Bp5'],
      objectives: [
        'Know that different animals are found in different habitats and explore how animals are adapted to their habitats',
        'Understand that habitats can change and this affects living things',
        'Construct and interpret food chains (producer, consumer, predator, prey)',
      ],
    },
    {
      id: 'science-4-animals',
      name: 'Animals and Humans',
      strand: 'Biology',
      codes: ['4Bs.01', '4Bs.02', '4Bp1', '4Bp2'],
      objectives: [
        'Identify vertebrates as animals with a backbone and invertebrates as animals without a backbone; know some animals have an exoskeleton',
        'Identify some important bones in the human body and describe important functions of skeletons (support, protection, movement)',
        'Know that human bodies have skeletons and muscles',
        'Explore how muscles work in pairs to enable movement',
      ],
    },
    {
      id: 'science-4-materials',
      name: 'Materials and Their Properties',
      strand: 'Chemistry',
      codes: ['4Cm.01', '4Cp.01', '4Cc.01', '4Cs1', '4Cs2', '4Cs3', '4Cs4'],
      objectives: [
        'Know that particles are in constant motion, even when in a solid',
        'Use the particle model to explain the properties of solids, liquids, and gases',
        'Describe solidification/freezing and melting using the particle model',
        'Know that matter can exist as solid, liquid, or gas',
        'Know that melting is when a solid turns into a liquid (reverse of freezing)',
        'Know that evaporation is when a liquid turns into a gas; boiling is evaporation at a specific temperature',
        'Observe how water turns into steam when heated but on cooling, steam turns back into water',
      ],
    },
    {
      id: 'science-4-forces',
      name: 'Forces and Motion',
      strand: 'Physics',
      codes: [],
      objectives: [],
    },
    {
      id: 'science-4-light-sound',
      name: 'Light and Sound',
      strand: 'Physics',
      codes: ['4Ps1', '4Ps2'],
      objectives: [
        'Explore how sounds are made when objects, materials, or air vibrate',
        'Explore how sounds travel through different materials to the ear',
      ],
    },
    {
      id: 'science-4-electricity',
      name: 'Electricity and Magnetism',
      strand: 'Physics',
      codes: ['4Pm1', '4Pm2', '4Pm3', '4Pe1', '4Pe2'],
      objectives: [
        'Know that magnets attract some metals but not others',
        'Explore how magnets have poles (north and south) and that like poles repel, unlike poles attract',
        'Predict whether magnets will attract or repel and investigate',
        'Construct simple circuits and switches; understand that a complete circuit is needed for a device to work',
        'Represent circuits with drawings and diagrams',
      ],
    },
    {
      id: 'science-4-enquiry',
      name: 'Scientific Enquiry',
      strand: 'Scientific Enquiry',
      codes: ['4Ep1', '4Ep2', '4Eo1', '4Eo2', '4Eo3', '4Eo4'],
      objectives: [
        'Collect evidence in a range of contexts; suggest and test ideas',
        'Plan investigations, considering variables to change, measure, and keep the same',
        'Make careful observations and measurements using a range of equipment',
        'Record results in tables, charts, and graphs',
        'Draw conclusions from results; identify evidence supporting conclusions',
        'Identify and explain patterns in results',
      ],
    },
  ],
  5: [
    {
      id: 'science-5-plants',
      name: 'Plants and Living Things',
      strand: 'Biology',
      codes: ['5Bp1', '5Bp2', '5Bp3', '5Bp4', '5Bp5', '5Bp6', '5Bp7'],
      objectives: [
        'Describe the parts of a flowering plant (sepals, petals, stamens, carpel)',
        'Know the stages in the life cycle of a flowering plant (germination, growth, reproduction, seed dispersal)',
        'Know that pollination is the transfer of pollen from stamen to carpel',
        'Know that fertilisation results in seed formation',
        'Know different methods of seed dispersal (wind, water, animals, explosive)',
        'Observe that plants produce flowers which have male and female organs; seeds are formed when pollen from the male organs reaches the female organs',
        'Recognise that flowering plants have a life cycle including pollination, fertilisation, seed production, seed dispersal, and germination',
      ],
    },
    {
      id: 'science-5-animals',
      name: 'Animals and Humans',
      strand: 'Biology',
      codes: [],
      objectives: [],
    },
    {
      id: 'science-5-materials',
      name: 'Materials and Their Properties',
      strand: 'Chemistry',
      codes: ['5Cm1', '5Cp1', '5Cp2', '5Cc.01', '5Cc1', '5Cc2', '5Cc3'],
      objectives: [
        'Know the differences between solids, liquids, and gases',
        'Explore dissolving — some solids dissolve in water, some do not',
        'Know that when a solid dissolves, it forms a solution',
        'Describe the processes of evaporation and condensation, using the particle model',
        'Explore how to recover a dissolved solid by evaporating the liquid',
        'Know that mixing and dissolving are reversible changes',
        'Explore how to separate mixtures (filtering, sieving, evaporation)',
      ],
    },
    {
      id: 'science-5-forces',
      name: 'Forces and Motion',
      strand: 'Physics',
      codes: ['5Pf1', '5Pf2', '5Pf3', '5Pf4'],
      objectives: [
        'Know that gravity is a force that pulls objects towards the Earth',
        'Know that friction is a force between surfaces that slows moving objects',
        'Know that air resistance and water resistance are forces',
        'Explore how forces can be measured with forcemeters (newtons)',
      ],
    },
    {
      id: 'science-5-light-sound',
      name: 'Light and Sound',
      strand: 'Physics',
      codes: ['5Pl1', '5Pl2', '5Pl3', '5Pl4'],
      objectives: [
        'Know that light travels in straight lines',
        'Know that we see objects because light from them enters our eyes',
        'Explore how shadows are formed when light is blocked',
        'Know that light is reflected from surfaces',
      ],
    },
    {
      id: 'science-5-electricity',
      name: 'Electricity and Magnetism',
      strand: 'Physics',
      codes: ['5Pe1', '5Pe2'],
      objectives: [
        'Construct and draw circuits with switches; know symbols for common components',
        'Investigate how the number of cells/batteries affects brightness of bulbs',
      ],
    },
    {
      id: 'science-5-earth',
      name: 'Earth and Space',
      strand: 'Earth and Space',
      codes: ['5ES1', '5ES2', '5ES3', '5ES4'],
      objectives: [
        'Know that the Earth orbits the Sun and the Moon orbits the Earth',
        'Know that the Earth rotates on its axis once every 24 hours, causing day and night',
        'Know that the Sun is a star and is at the centre of our solar system',
        'Know the order of the planets from the Sun',
      ],
    },
    {
      id: 'science-5-enquiry',
      name: 'Scientific Enquiry',
      strand: 'Scientific Enquiry',
      codes: ['5Ep1', '5Ep2', '5Ep3', '5Eo1', '5Eo2', '5Eo3', '5Eo4'],
      objectives: [
        'Plan investigations selecting variables and procedures',
        'Make predictions based on scientific knowledge',
        'Identify appropriate evidence to collect',
        'Make accurate observations and measurements',
        'Record and present results appropriately',
        'Draw conclusions from results and use scientific understanding to explain',
        'Identify and evaluate patterns in results',
      ],
    },
  ],
  6: [
    {
      id: 'science-6-plants',
      name: 'Plants and Living Things',
      strand: 'Biology',
      codes: [],
      objectives: [],
    },
    {
      id: 'science-6-animals',
      name: 'Animals and Humans',
      strand: 'Biology',
      codes: ['6Bs.01', '6Bs.02', '6Bp.02', '6Bp.03', '6Bp.04', '6Bp1', '6Bp2', '6Bp3'],
      objectives: [
        'Describe the human circulatory system: heart pumping blood through arteries, capillaries, and veins; function limited to transporting oxygen, nutrients, and waste',
        'Describe the human respiratory system: oxygen from air moving into the blood in the lungs; know that many vertebrates have a similar respiratory system',
        'Know that some diseases can be caused by infection with viruses, bacteria, parasites, or fungi that can be passed from one host to another',
        'Describe how good hygiene can control the spread of diseases transmitted in water, food, and body fluids; describe ways to avoid being bitten by insect vectors',
        'Know that humans have defence mechanisms against infectious diseases, including skin, stomach acid, and mucus',
        'Know the basic structure and function of the human circulatory system (heart, blood vessels, blood)',
        'Know the effect of exercise and diet on health',
        'Know that some diseases can be prevented by vaccination',
      ],
    },
    {
      id: 'science-6-materials',
      name: 'Materials and Their Properties',
      strand: 'Chemistry',
      codes: ['6Cp.01', '6Cp.02', '6Cc.01', '6Cc.03', '6Cc1', '6Cc2', '6Cc3'],
      objectives: [
        'Know that the temperature at which a substance changes state is a property of the substance',
        'Know that gases have properties including mass',
        'Identify and describe physical changes that are reversible',
        'Describe the difference between boiling and evaporation',
        'Distinguish between reversible and irreversible changes',
        'Explore how heating can cause irreversible changes (burning, cooking)',
        'Know that new materials are formed during irreversible changes',
      ],
    },
    {
      id: 'science-6-forces',
      name: 'Forces and Motion',
      strand: 'Physics',
      codes: ['6Pf.01', '6Pf.02', '6Pf.03', '6Pf.04', '6Pf.05'],
      objectives: [
        'Describe the difference between mass (kilograms) and weight (newtons)',
        'Describe the effect of gravity; when gravity changes, weight changes but mass does not',
        'Use force diagrams to show name, size, and direction of forces acting on an object',
        'Describe the effect of different forces on an object at rest and in motion',
        'Recognise that the mass and shape of an object can affect if it floats or sinks',
      ],
    },
    {
      id: 'science-6-light-sound',
      name: 'Light and Sound',
      strand: 'Physics',
      codes: ['6Pl1', '6Pl2', '6Pl3'],
      objectives: [
        'Know that white light is made up of different colours',
        'Explore how light can be dispersed using a prism',
        'Know how the eye works (basic structure)',
      ],
    },
    {
      id: 'science-6-electricity',
      name: 'Electricity and Magnetism',
      strand: 'Physics',
      codes: ['6Pe1', '6Pe2'],
      objectives: [
        'Know that changing the components in a circuit can affect it (e.g. adding more bulbs, changing wire length)',
        'Know and use conventional circuit symbols',
      ],
    },
    {
      id: 'science-6-earth',
      name: 'Earth and Space',
      strand: 'Earth and Space',
      codes: ['6ESs.01', '6ESp.01', '6ESp.02', '6ESc.01', '6ES1', '6ES2', '6ES3'],
      objectives: [
        'Describe the relative position and movement of the planets, the Moon, and the Sun in the Solar System',
        'Know that rocks can be classified as metamorphic, igneous, and sedimentary; describe the identifying features of each type',
        'Describe the way fossils can form in sedimentary rocks',
        'Describe the rock cycle and the formation of metamorphic, igneous, and sedimentary rocks, in terms of solidification, erosion, sedimentation, burial, metamorphism, and melting',
        'Know the components of the solar system',
        'Know that the Earth, Sun, and Moon are approximately spherical',
        'Explore how different rocks are formed',
      ],
    },
    {
      id: 'science-6-enquiry',
      name: 'Scientific Enquiry',
      strand: 'Scientific Enquiry',
      codes: ['6Ep1', '6Ep2', '6Eo1', '6Eo2', '6Eo3', '6Eo4'],
      objectives: [
        'Plan investigations with control of variables',
        'Make predictions and identify evidence to collect',
        'Make precise measurements with appropriate equipment',
        'Record and present results systematically',
        'Draw conclusions, identify limitations, suggest improvements',
        'Evaluate investigations and identify further questions',
      ],
    },
  ],
};

module.exports = science;
